begin;

alter table public.user_permissions
drop constraint if exists user_permissions_module_check;

alter table public.user_permissions
add constraint user_permissions_module_check check (
  module in (
    'dashboard',
    'tutores',
    'pets',
    'servicos',
    'agenda',
    'financeiro',
    'recibos',
    'relatorios',
    'pdv',
    'configuracoes',
    'usuarios'
  )
);

insert into public.user_permissions (user_id, module, can_access)
select id, 'pdv', is_admin
from public.user_profiles
on conflict (user_id, module) do update
set can_access = excluded.can_access
where public.user_permissions.can_access = false;

create or replace function public.create_default_user_permissions(target_user_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.user_permissions (user_id, module, can_access)
  select
    target_user_id,
    module,
    false
  from unnest(
    array[
      'dashboard',
      'tutores',
      'pets',
      'servicos',
      'agenda',
      'financeiro',
      'recibos',
      'relatorios',
      'pdv',
      'configuracoes',
      'usuarios'
    ]
  ) as modules(module)
  on conflict (user_id, module) do nothing;
$$;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  nome text not null,
  sku text unique,
  categoria text,
  preco_custo numeric(12, 2) not null default 0 check (preco_custo >= 0),
  preco_venda numeric(12, 2) not null check (preco_venda >= 0),
  estoque integer not null default 0 check (estoque >= 0),
  estoque_minimo integer not null default 0 check (estoque_minimo >= 0),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_quotes (
  id bigint generated by default as identity primary key,
  tutor_id bigint references public.tutors(id) on delete set null,
  cliente_nome text,
  total numeric(12, 2) not null check (total >= 0),
  validade date,
  status text not null default 'Aberto'
    check (status in ('Aberto', 'Convertido', 'Cancelado')),
  created_at timestamptz not null default now()
);

create table if not exists public.pos_quote_items (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.pos_quotes(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  descricao text not null,
  quantidade integer not null check (quantidade > 0),
  valor_unitario numeric(12, 2) not null check (valor_unitario >= 0),
  subtotal numeric(12, 2) not null check (subtotal >= 0)
);

create table if not exists public.pos_sales (
  id bigint generated by default as identity primary key,
  tutor_id bigint references public.tutors(id) on delete set null,
  cliente_nome text,
  total numeric(12, 2) not null check (total >= 0),
  forma_pagamento text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.pos_sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.pos_sales(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  descricao text not null,
  quantidade integer not null check (quantidade > 0),
  valor_unitario numeric(12, 2) not null check (valor_unitario >= 0),
  subtotal numeric(12, 2) not null check (subtotal >= 0)
);

alter table public.products enable row level security;
alter table public.pos_quotes enable row level security;
alter table public.pos_quote_items enable row level security;
alter table public.pos_sales enable row level security;
alter table public.pos_sale_items enable row level security;

drop policy if exists "PDV users can manage products" on public.products;
create policy "PDV users can manage products"
on public.products for all to authenticated
using (public.current_user_can_access('pdv'))
with check (public.current_user_can_access('pdv'));

drop policy if exists "PDV users can read quotes" on public.pos_quotes;
create policy "PDV users can read quotes"
on public.pos_quotes for select to authenticated
using (public.current_user_can_access('pdv'));

drop policy if exists "PDV users can read quote items" on public.pos_quote_items;
create policy "PDV users can read quote items"
on public.pos_quote_items for select to authenticated
using (public.current_user_can_access('pdv'));

drop policy if exists "PDV users can read sales" on public.pos_sales;
create policy "PDV users can read sales"
on public.pos_sales for select to authenticated
using (public.current_user_can_access('pdv'));

drop policy if exists "PDV users can read sale items" on public.pos_sale_items;
create policy "PDV users can read sale items"
on public.pos_sale_items for select to authenticated
using (public.current_user_can_access('pdv'));

grant select, insert, update, delete on public.products to authenticated;
grant select on public.pos_quotes, public.pos_quote_items to authenticated;
grant select on public.pos_sales, public.pos_sale_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.create_pos_quote(
  customer_tutor_id bigint,
  customer_name text,
  expiration_date date,
  items jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_quote_id bigint;
  item jsonb;
  quote_total numeric(12, 2) := 0;
  product_record public.products%rowtype;
  item_quantity integer;
begin
  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao PDV';
  end if;

  if jsonb_array_length(items) = 0 then
    raise exception 'O orçamento precisa ter ao menos um item';
  end if;

  for item in select * from jsonb_array_elements(items)
  loop
    select * into product_record
    from public.products
    where id = (item ->> 'product_id')::bigint
      and ativo = true;

    if not found then
      raise exception 'Produto inválido';
    end if;

    item_quantity := (item ->> 'quantidade')::integer;
    if item_quantity <= 0 then
      raise exception 'Quantidade inválida';
    end if;

    quote_total := quote_total + (product_record.preco_venda * item_quantity);
  end loop;

  insert into public.pos_quotes (
    tutor_id,
    cliente_nome,
    total,
    validade
  )
  values (
    customer_tutor_id,
    nullif(trim(customer_name), ''),
    quote_total,
    expiration_date
  )
  returning id into new_quote_id;

  for item in select * from jsonb_array_elements(items)
  loop
    select * into product_record
    from public.products
    where id = (item ->> 'product_id')::bigint;

    item_quantity := (item ->> 'quantidade')::integer;

    insert into public.pos_quote_items (
      quote_id,
      product_id,
      descricao,
      quantidade,
      valor_unitario,
      subtotal
    )
    values (
      new_quote_id,
      product_record.id,
      product_record.nome,
      item_quantity,
      product_record.preco_venda,
      product_record.preco_venda * item_quantity
    );
  end loop;

  return new_quote_id;
end;
$$;

create or replace function public.create_pos_sale(
  customer_tutor_id bigint,
  customer_name text,
  payment_method text,
  items jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_sale_id bigint;
  item jsonb;
  sale_total numeric(12, 2) := 0;
  product_record public.products%rowtype;
  item_quantity integer;
begin
  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao PDV';
  end if;

  if jsonb_array_length(items) = 0 then
    raise exception 'A venda precisa ter ao menos um item';
  end if;

  for item in select * from jsonb_array_elements(items)
  loop
    select * into product_record
    from public.products
    where id = (item ->> 'product_id')::bigint
      and ativo = true
    for update;

    if not found then
      raise exception 'Produto inválido';
    end if;

    item_quantity := (item ->> 'quantidade')::integer;
    if item_quantity <= 0 or product_record.estoque < item_quantity then
      raise exception 'Estoque insuficiente para %', product_record.nome;
    end if;

    sale_total := sale_total + (product_record.preco_venda * item_quantity);
  end loop;

  insert into public.pos_sales (
    tutor_id,
    cliente_nome,
    total,
    forma_pagamento
  )
  values (
    customer_tutor_id,
    nullif(trim(customer_name), ''),
    sale_total,
    payment_method
  )
  returning id into new_sale_id;

  for item in select * from jsonb_array_elements(items)
  loop
    select * into product_record
    from public.products
    where id = (item ->> 'product_id')::bigint
    for update;

    item_quantity := (item ->> 'quantidade')::integer;

    insert into public.pos_sale_items (
      sale_id,
      product_id,
      descricao,
      quantidade,
      valor_unitario,
      subtotal
    )
    values (
      new_sale_id,
      product_record.id,
      product_record.nome,
      item_quantity,
      product_record.preco_venda,
      product_record.preco_venda * item_quantity
    );

    update public.products
    set
      estoque = estoque - item_quantity,
      updated_at = now()
    where id = product_record.id;
  end loop;

  insert into public.financial_entries (
    descricao,
    valor,
    tipo,
    forma_pagamento,
    status_pagamento
  )
  values (
    format('Venda PDV #%s - %s', new_sale_id, coalesce(nullif(trim(customer_name), ''), 'Consumidor')),
    sale_total,
    'Receita',
    payment_method,
    'Pago'
  );

  return new_sale_id;
end;
$$;

revoke all on function public.create_pos_quote(bigint, text, date, jsonb) from public;
revoke all on function public.create_pos_sale(bigint, text, text, jsonb) from public;
grant execute on function public.create_pos_quote(bigint, text, date, jsonb) to authenticated;
grant execute on function public.create_pos_sale(bigint, text, text, jsonb) to authenticated;

commit;
