begin;

create sequence if not exists public.product_code_seq start 1;

create or replace function public.generate_product_code()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.sku is null or trim(new.sku) = '' then
    loop
      new.sku :=
        'PM' || lpad(nextval('public.product_code_seq')::text, 6, '0');

      exit when not exists (
        select 1 from public.products where sku = new.sku
      );
    end loop;
  end if;

  return new;
end;
$$;

drop trigger if exists set_product_code on public.products;

create trigger set_product_code
before insert or update of sku on public.products
for each row execute function public.generate_product_code();

update public.products
set sku = null
where sku is null or trim(sku) = '';

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  nome text not null,
  documento text,
  telefone text,
  email text,
  contato text,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_purchases (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete restrict,
  numero_documento text,
  data_compra date not null default current_date,
  total numeric(12, 2) not null check (total >= 0),
  observacao text,
  created_at timestamptz not null default now()
);

create table if not exists public.product_purchase_items (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null
    references public.product_purchases(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantidade integer not null check (quantidade > 0),
  custo_unitario numeric(12, 2) not null check (custo_unitario >= 0),
  subtotal numeric(12, 2) not null check (subtotal >= 0)
);

alter table public.suppliers enable row level security;
alter table public.product_purchases enable row level security;
alter table public.product_purchase_items enable row level security;

drop policy if exists "PDV users can manage suppliers" on public.suppliers;
create policy "PDV users can manage suppliers"
on public.suppliers for all to authenticated
using (public.current_user_can_access('pdv'))
with check (public.current_user_can_access('pdv'));

drop policy if exists "PDV users can read purchases" on public.product_purchases;
create policy "PDV users can read purchases"
on public.product_purchases for select to authenticated
using (public.current_user_can_access('pdv'));

drop policy if exists "PDV users can read purchase items"
on public.product_purchase_items;
create policy "PDV users can read purchase items"
on public.product_purchase_items for select to authenticated
using (public.current_user_can_access('pdv'));

grant select, insert, update, delete on public.suppliers to authenticated;
grant select on public.product_purchases, public.product_purchase_items
to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.create_product_purchase(
  selected_supplier_id bigint,
  document_number text,
  purchase_date date,
  notes text,
  items jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_purchase_id bigint;
  purchase_total numeric(12, 2) := 0;
  item jsonb;
  selected_product public.products%rowtype;
  item_quantity integer;
  item_cost numeric(12, 2);
begin
  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao PDV';
  end if;

  if not exists (
    select 1 from public.suppliers
    where id = selected_supplier_id and ativo = true
  ) then
    raise exception 'Fornecedor inválido';
  end if;

  if items is null
    or jsonb_typeof(items) <> 'array'
    or jsonb_array_length(items) = 0
  then
    raise exception 'A compra precisa ter ao menos um item';
  end if;

  for item in select * from jsonb_array_elements(items)
  loop
    select * into selected_product
    from public.products
    where id = (item ->> 'product_id')::bigint
    for update;

    if not found then
      raise exception 'Produto inválido';
    end if;

    item_quantity := (item ->> 'quantidade')::integer;
    item_cost := (item ->> 'custo_unitario')::numeric;

    if item_quantity <= 0 or item_cost < 0 then
      raise exception 'Quantidade ou custo inválido';
    end if;

    purchase_total := purchase_total + (item_quantity * item_cost);
  end loop;

  insert into public.product_purchases (
    supplier_id,
    numero_documento,
    data_compra,
    total,
    observacao
  )
  values (
    selected_supplier_id,
    nullif(trim(document_number), ''),
    coalesce(purchase_date, current_date),
    purchase_total,
    nullif(trim(notes), '')
  )
  returning id into new_purchase_id;

  for item in select * from jsonb_array_elements(items)
  loop
    select * into selected_product
    from public.products
    where id = (item ->> 'product_id')::bigint
    for update;

    item_quantity := (item ->> 'quantidade')::integer;
    item_cost := (item ->> 'custo_unitario')::numeric;

    insert into public.product_purchase_items (
      purchase_id,
      product_id,
      quantidade,
      custo_unitario,
      subtotal
    )
    values (
      new_purchase_id,
      selected_product.id,
      item_quantity,
      item_cost,
      item_quantity * item_cost
    );

    update public.products
    set
      estoque = estoque + item_quantity,
      preco_custo = item_cost,
      updated_at = now()
    where id = selected_product.id;
  end loop;

  return new_purchase_id;
end;
$$;

revoke all on function public.create_product_purchase(
  bigint,
  text,
  date,
  text,
  jsonb
) from public;

grant execute on function public.create_product_purchase(
  bigint,
  text,
  date,
  text,
  jsonb
) to authenticated;

commit;
