begin;

create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  nome text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists product_categories_nome_unique
on public.product_categories (lower(trim(nome)));

insert into public.product_categories (nome)
values
  ('Rações'),
  ('Petiscos'),
  ('Higiene'),
  ('Vestuário'),
  ('Coleiras e Guias'),
  ('Brinquedos'),
  ('Camas e Acessórios'),
  ('Transporte'),
  ('Outros')
on conflict do nothing;

insert into public.product_categories (nome)
select distinct trim(categoria)
from public.products
where categoria is not null
  and trim(categoria) <> ''
on conflict do nothing;

alter table public.products
add column if not exists category_id bigint
references public.product_categories(id) on delete set null;

alter table public.products
add column if not exists tamanho text;

alter table public.products
add column if not exists cor text;

alter table public.products
add column if not exists sabor text;

update public.products as product
set category_id = category.id
from public.product_categories as category
where product.category_id is null
  and product.categoria is not null
  and lower(trim(product.categoria)) = lower(trim(category.nome));

alter table public.product_categories enable row level security;

drop policy if exists "PDV users can manage categories"
on public.product_categories;

create policy "PDV users can manage categories"
on public.product_categories for all to authenticated
using (public.current_user_can_access('pdv'))
with check (public.current_user_can_access('pdv'));

grant select, insert, update, delete
on public.product_categories to authenticated;

create or replace function public.set_pos_item_product_description()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_product public.products%rowtype;
  variation text;
begin
  if new.product_id is null then
    return new;
  end if;

  select * into selected_product
  from public.products
  where id = new.product_id;

  if not found then
    return new;
  end if;

  variation := concat_ws(
    ' / ',
    nullif(trim(selected_product.tamanho), ''),
    nullif(trim(selected_product.cor), ''),
    nullif(trim(selected_product.sabor), '')
  );

  new.descricao := selected_product.nome
    || case when variation = '' then '' else ' - ' || variation end;

  return new;
end;
$$;

drop trigger if exists set_quote_item_product_description
on public.pos_quote_items;

create trigger set_quote_item_product_description
before insert or update of product_id
on public.pos_quote_items
for each row execute function public.set_pos_item_product_description();

drop trigger if exists set_sale_item_product_description
on public.pos_sale_items;

create trigger set_sale_item_product_description
before insert or update of product_id
on public.pos_sale_items
for each row execute function public.set_pos_item_product_description();

commit;
