begin;

create table if not exists public.clinical_records (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  professional_id uuid references public.user_profiles(id) on delete set null,
  professional_name text not null,
  consultation_date date not null default current_date,
  weight_kg numeric(6, 2) check (weight_kg is null or weight_kg > 0),
  temperature_c numeric(4, 1)
    check (temperature_c is null or temperature_c between 30 and 45),
  main_complaint text not null,
  diagnosis text,
  conduct text,
  return_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists clinical_records_pet_date_idx
on public.clinical_records (pet_id, consultation_date desc, created_at desc);

alter table public.clinical_records enable row level security;

drop policy if exists "Pet users can manage clinical records"
on public.clinical_records;

create policy "Pet users can manage clinical records"
on public.clinical_records for all to authenticated
using (public.current_user_can_access('pets'))
with check (public.current_user_can_access('pets'));

grant select, insert, update, delete
on public.clinical_records to authenticated;

grant usage, select on all sequences in schema public to authenticated;

commit;
