begin;

alter table public.clinical_records
add column if not exists anamnesis text;

alter table public.clinical_records
add column if not exists allergies text;

alter table public.clinical_records
add column if not exists current_medications text;

create table if not exists public.clinical_prescriptions (
  id bigint generated by default as identity primary key,
  clinical_record_id bigint not null
    references public.clinical_records(id) on delete cascade,
  medication text not null,
  dosage text not null,
  frequency text not null,
  duration text,
  instructions text,
  created_at timestamptz not null default now()
);

create index if not exists clinical_prescriptions_record_idx
on public.clinical_prescriptions (clinical_record_id, created_at);

alter table public.clinical_prescriptions enable row level security;

drop policy if exists "Pet users can manage clinical prescriptions"
on public.clinical_prescriptions;

create policy "Pet users can manage clinical prescriptions"
on public.clinical_prescriptions for all to authenticated
using (public.current_user_can_access('pets'))
with check (public.current_user_can_access('pets'));

grant select, insert, update, delete
on public.clinical_prescriptions to authenticated;

grant usage, select on all sequences in schema public to authenticated;

commit;
