begin;

create table if not exists public.pet_vaccinations (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  vaccine_name text not null,
  manufacturer text,
  batch_number text,
  application_date date not null default current_date,
  next_dose_date date,
  professional_name text not null,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists pet_vaccinations_pet_date_idx
on public.pet_vaccinations (pet_id, application_date desc);

alter table public.pet_vaccinations enable row level security;

drop policy if exists "Pet users can manage vaccinations"
on public.pet_vaccinations;

create policy "Pet users can manage vaccinations"
on public.pet_vaccinations for all to authenticated
using (public.current_user_can_access('pets'))
with check (public.current_user_can_access('pets'));

grant select, insert, update, delete
on public.pet_vaccinations to authenticated;

grant usage, select on all sequences in schema public to authenticated;

commit;
