begin;

create table if not exists public.clinical_exams (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  clinical_record_id bigint
    references public.clinical_records(id) on delete set null,
  exam_name text not null,
  request_date date not null default current_date,
  collection_date date,
  result_date date,
  laboratory text,
  status text not null default 'Solicitado'
    check (status in ('Solicitado', 'Coletado', 'Concluído', 'Cancelado')),
  result text,
  notes text,
  professional_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists clinical_exams_pet_date_idx
on public.clinical_exams (pet_id, request_date desc);

alter table public.clinical_exams enable row level security;

create policy "Clinic users can manage clinical exams"
on public.clinical_exams for all to authenticated
using (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
)
with check (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
);

grant select, insert, update, delete
on public.clinical_exams to authenticated;

grant usage, select on all sequences in schema public to authenticated;

commit;
