begin;

alter table public.user_permissions
drop constraint if exists user_permissions_module_check;

alter table public.user_permissions
add constraint user_permissions_module_check check (
  module in (
    'dashboard',
    'tutores',
    'pets',
    'servicos',
    'agenda',
    'financeiro',
    'recibos',
    'relatorios',
    'pdv',
    'clinica',
    'crm',
    'bi',
    'configuracoes',
    'usuarios'
  )
);

insert into public.user_permissions (user_id, module, can_access)
select id, module, is_admin
from public.user_profiles
cross join unnest(array['crm', 'bi']) as modules(module)
on conflict (user_id, module) do nothing;

create or replace function public.create_default_user_permissions(
  target_user_id uuid
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.user_permissions (user_id, module, can_access)
  select target_user_id, module, false
  from unnest(
    array[
      'dashboard',
      'tutores',
      'pets',
      'servicos',
      'agenda',
      'financeiro',
      'recibos',
      'relatorios',
      'pdv',
      'clinica',
      'crm',
      'bi',
      'configuracoes',
      'usuarios'
    ]
  ) as modules(module)
  on conflict (user_id, module) do nothing;
$$;

create table if not exists public.crm_interactions (
  id bigint generated by default as identity primary key,
  tutor_id bigint not null references public.tutors(id) on delete cascade,
  contact_date date not null default current_date,
  channel text not null,
  subject text not null,
  notes text,
  next_action_date date,
  status text not null default 'Aberto'
    check (status in ('Aberto', 'Concluído')),
  responsible_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists crm_interactions_tutor_date_idx
on public.crm_interactions (tutor_id, contact_date desc);

alter table public.crm_interactions enable row level security;

create policy "CRM users can manage interactions"
on public.crm_interactions for all to authenticated
using (public.current_user_can_access('crm'))
with check (public.current_user_can_access('crm'));

grant select, insert, update, delete
on public.crm_interactions to authenticated;

grant usage, select on all sequences in schema public to authenticated;

commit;
