begin;

create table if not exists public.clinical_documents (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  document_type text not null
    check (document_type in ('Atestado', 'Declaração', 'Orientação')),
  title text not null,
  content text not null,
  issue_date date not null default current_date,
  professional_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists clinical_documents_pet_date_idx
on public.clinical_documents (pet_id, issue_date desc);

alter table public.clinical_documents enable row level security;

create policy "Clinic users can manage clinical documents"
on public.clinical_documents for all to authenticated
using (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
)
with check (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
);

grant select, insert, update, delete
on public.clinical_documents to authenticated;

grant usage, select on all sequences in schema public to authenticated;

commit;
