begin;

create table if not exists public.clinical_attachments (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  clinical_exam_id bigint references public.clinical_exams(id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 10485760),
  uploaded_by uuid references public.user_profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists clinical_attachments_pet_idx
on public.clinical_attachments (pet_id, created_at desc);

create index if not exists clinical_attachments_exam_idx
on public.clinical_attachments (clinical_exam_id, created_at desc);

alter table public.clinical_attachments enable row level security;

drop policy if exists "Clinic users can manage clinical attachments"
on public.clinical_attachments;

create policy "Clinic users can manage clinical attachments"
on public.clinical_attachments for all to authenticated
using (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
)
with check (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
);

grant select, insert, update, delete
on public.clinical_attachments to authenticated;

grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'clinical-attachments',
  'clinical-attachments',
  false,
  10485760,
  array['application/pdf', 'image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Clinic users can read clinical files"
on storage.objects;
create policy "Clinic users can read clinical files"
on storage.objects for select to authenticated
using (
  bucket_id = 'clinical-attachments'
  and (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  )
);

drop policy if exists "Clinic users can upload clinical files"
on storage.objects;
create policy "Clinic users can upload clinical files"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'clinical-attachments'
  and (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  )
);

drop policy if exists "Clinic users can delete clinical files"
on storage.objects;
create policy "Clinic users can delete clinical files"
on storage.objects for delete to authenticated
using (
  bucket_id = 'clinical-attachments'
  and (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  )
);

commit;
