begin;

alter table public.user_profiles
add column if not exists crmv text;

alter table public.user_profiles
add column if not exists especialidade text;

alter table public.clinical_records
add column if not exists professional_crmv text;

alter table public.clinical_documents
add column if not exists professional_crmv text;

drop policy if exists "Users can update own professional profile"
on public.user_profiles;
create policy "Users can update own professional profile"
on public.user_profiles for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

grant update (crmv, especialidade)
on public.user_profiles to authenticated;

create table if not exists public.clinical_audit_logs (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id bigint not null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  changed_by uuid references public.user_profiles(id) on delete set null,
  old_data jsonb,
  new_data jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists clinical_audit_logs_entity_idx
on public.clinical_audit_logs (entity_type, entity_id, changed_at desc);

alter table public.clinical_audit_logs enable row level security;

drop policy if exists "Clinic users can read clinical audit logs"
on public.clinical_audit_logs;
create policy "Clinic users can read clinical audit logs"
on public.clinical_audit_logs for select to authenticated
using (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
);

drop policy if exists "Authenticated users can insert own clinical audit logs"
on public.clinical_audit_logs;
create policy "Authenticated users can insert own clinical audit logs"
on public.clinical_audit_logs for insert to authenticated
with check (changed_by = (select auth.uid()));

grant select, insert on public.clinical_audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.log_clinical_change()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  row_id bigint;
begin
  row_id := case when tg_op = 'DELETE' then old.id else new.id end;

  insert into public.clinical_audit_logs (
    entity_type,
    entity_id,
    action,
    changed_by,
    old_data,
    new_data
  ) values (
    tg_table_name,
    row_id,
    tg_op,
    (select auth.uid()),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function public.log_clinical_change() from public;
grant execute on function public.log_clinical_change() to authenticated;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'clinical_records',
    'clinical_prescriptions',
    'pet_vaccinations',
    'clinical_exams',
    'clinical_documents',
    'clinical_attachments'
  ] loop
    execute format(
      'drop trigger if exists audit_clinical_changes on public.%I',
      table_name
    );
    execute format(
      'create trigger audit_clinical_changes after insert or update or delete on public.%I for each row execute function public.log_clinical_change()',
      table_name
    );
  end loop;
end;
$$;

commit;
