begin;

create table if not exists public.clinical_prescription_documents (
  id bigint generated by default as identity primary key,
  clinical_record_id bigint not null
    references public.clinical_records(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  issue_date date not null default current_date,
  general_instructions text,
  status text not null default 'rascunho'
    check (status in ('rascunho', 'emitida', 'cancelada')),
  professional_id uuid references public.user_profiles(id) on delete set null,
  professional_name text not null,
  professional_crmv text,
  issued_at timestamptz,
  source_record_id bigint unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.clinical_prescriptions
add column if not exists prescription_document_id bigint
references public.clinical_prescription_documents(id) on delete cascade;

create index if not exists clinical_prescription_documents_pet_date_idx
on public.clinical_prescription_documents (pet_id, issue_date desc);

create index if not exists clinical_prescription_documents_record_idx
on public.clinical_prescription_documents (clinical_record_id, created_at desc);

create index if not exists clinical_prescriptions_document_idx
on public.clinical_prescriptions (prescription_document_id, created_at);

alter table public.clinical_prescription_documents enable row level security;

drop policy if exists "Clinic users can manage prescription documents"
on public.clinical_prescription_documents;

create policy "Clinic users can manage prescription documents"
on public.clinical_prescription_documents for all to authenticated
using (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
)
with check (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
);

grant select, insert, update, delete
on public.clinical_prescription_documents to authenticated;

grant usage, select on all sequences in schema public to authenticated;

insert into public.clinical_prescription_documents (
  clinical_record_id,
  pet_id,
  issue_date,
  status,
  professional_id,
  professional_name,
  professional_crmv,
  issued_at,
  source_record_id,
  created_at,
  updated_at
)
select
  record.id,
  record.pet_id,
  record.consultation_date,
  'emitida',
  record.professional_id,
  record.professional_name,
  record.professional_crmv,
  record.created_at,
  record.id,
  record.created_at,
  now()
from public.clinical_records record
where exists (
  select 1
  from public.clinical_prescriptions prescription
  where prescription.clinical_record_id = record.id
)
on conflict (source_record_id) do nothing;

update public.clinical_prescriptions prescription
set prescription_document_id = document.id
from public.clinical_prescription_documents document
where prescription.prescription_document_id is null
  and document.source_record_id = prescription.clinical_record_id;

do $$
begin
  if to_regprocedure('public.log_clinical_change()') is not null then
    drop trigger if exists audit_clinical_changes
    on public.clinical_prescription_documents;

    create trigger audit_clinical_changes
    after insert or update or delete
    on public.clinical_prescription_documents
    for each row execute function public.log_clinical_change();
  end if;
end;
$$;

commit;

select
  (select count(*) from public.clinical_prescription_documents)
    as prescription_documents,
  (select count(*) from public.clinical_prescriptions
   where prescription_document_id is not null)
    as linked_prescription_items,
  (select count(*) from public.clinical_prescriptions
   where prescription_document_id is null)
    as unlinked_prescription_items;
