begin;

create table if not exists public.medication_catalog (
  id bigint generated by default as identity primary key,
  name text not null,
  active_ingredient text,
  default_pharmacy_type text
    check (default_pharmacy_type in ('veterinaria', 'humana', 'manipulacao')),
  default_pharmaceutical_form text,
  default_administration_route text,
  notes text,
  is_favorite boolean not null default false,
  is_active boolean not null default true,
  created_by uuid references public.user_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists medication_catalog_name_unique_idx
on public.medication_catalog (lower(name));

create index if not exists medication_catalog_search_idx
on public.medication_catalog (is_active, is_favorite desc, name);

create table if not exists public.medication_dosage_templates (
  id bigint generated by default as identity primary key,
  medication_id bigint not null
    references public.medication_catalog(id) on delete cascade,
  name text not null,
  species text,
  dosage text not null,
  frequency text not null,
  duration text,
  instructions text,
  created_by uuid references public.user_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists medication_dosage_templates_medication_idx
on public.medication_dosage_templates (medication_id, species, name);

create table if not exists public.prescription_formula_components (
  id bigint generated by default as identity primary key,
  clinical_prescription_id bigint not null
    references public.clinical_prescriptions(id) on delete cascade,
  component_name text not null,
  concentration text not null,
  unit text,
  sort_order smallint not null default 1 check (sort_order > 0),
  created_at timestamptz not null default now()
);

create index if not exists prescription_formula_components_item_idx
on public.prescription_formula_components (
  clinical_prescription_id,
  sort_order,
  id
);

alter table public.medication_catalog enable row level security;
alter table public.medication_dosage_templates enable row level security;
alter table public.prescription_formula_components enable row level security;

drop policy if exists "Clinic users can manage medication catalog"
on public.medication_catalog;
create policy "Clinic users can manage medication catalog"
on public.medication_catalog for all to authenticated
using (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
)
with check (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
);

drop policy if exists "Clinic users can manage medication templates"
on public.medication_dosage_templates;
create policy "Clinic users can manage medication templates"
on public.medication_dosage_templates for all to authenticated
using (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
)
with check (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
);

drop policy if exists "Clinic users can manage formula components"
on public.prescription_formula_components;
create policy "Clinic users can manage formula components"
on public.prescription_formula_components for all to authenticated
using (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
)
with check (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
);

grant select, insert, update, delete
on public.medication_catalog,
   public.medication_dosage_templates,
   public.prescription_formula_components
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

insert into public.medication_catalog (name, active_ingredient)
values
  ('Amoxicilina', 'Amoxicilina'),
  ('Amoxicilina + clavulanato', 'Amoxicilina + ácido clavulânico'),
  ('Cefalexina', 'Cefalexina'),
  ('Doxiciclina', 'Doxiciclina'),
  ('Enrofloxacino', 'Enrofloxacino'),
  ('Meloxicam', 'Meloxicam'),
  ('Prednisolona', 'Prednisolona'),
  ('Dipirona', 'Metamizol'),
  ('Omeprazol', 'Omeprazol'),
  ('Ondansetrona', 'Ondansetrona'),
  ('Metronidazol', 'Metronidazol')
on conflict do nothing;

do $$
declare
  table_name text;
begin
  if to_regprocedure('public.log_clinical_change()') is not null then
    foreach table_name in array array[
      'medication_catalog',
      'medication_dosage_templates',
      'prescription_formula_components'
    ] loop
      execute format(
        'drop trigger if exists audit_clinical_changes on public.%I',
        table_name
      );
      execute format(
        'create trigger audit_clinical_changes after insert or update or delete on public.%I for each row execute function public.log_clinical_change()',
        table_name
      );
    end loop;
  end if;
end;
$$;

commit;

select
  (select count(*) from public.medication_catalog) as medications,
  (select count(*) from public.medication_dosage_templates) as dosage_templates,
  (select count(*) from public.prescription_formula_components)
    as formula_components;
