begin;

create table if not exists public.clinical_prescription_reissues (
  id bigint generated by default as identity primary key,
  prescription_document_id bigint not null
    references public.clinical_prescription_documents(id) on delete cascade,
  previous_share_token uuid,
  new_share_token uuid not null,
  reason text,
  reissued_by uuid references public.user_profiles(id) on delete set null,
  reissued_at timestamptz not null default now()
);

create index if not exists clinical_prescription_reissues_document_idx
on public.clinical_prescription_reissues (
  prescription_document_id,
  reissued_at desc
);

alter table public.clinical_prescription_reissues enable row level security;

drop policy if exists "Clinic users can read prescription reissues"
on public.clinical_prescription_reissues;
create policy "Clinic users can read prescription reissues"
on public.clinical_prescription_reissues for select to authenticated
using (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
);

drop policy if exists "Clinic users can insert prescription reissues"
on public.clinical_prescription_reissues;
create policy "Clinic users can insert prescription reissues"
on public.clinical_prescription_reissues for insert to authenticated
with check (
  reissued_by = (select auth.uid())
  and (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  )
);

grant select, insert
on public.clinical_prescription_reissues to authenticated;

grant usage, select on all sequences in schema public to authenticated;

create or replace function public.rotate_prescription_share_token(
  requested_document_id bigint,
  reissue_reason text default null
)
returns table (
  share_token uuid,
  reissue_count integer,
  last_reissued_at timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  previous_token uuid;
  generated_token uuid := gen_random_uuid();
begin
  if not (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  ) then
    raise exception 'Acesso negado ao modulo clinico';
  end if;

  select document.share_token
  into previous_token
  from public.clinical_prescription_documents document
  where document.id = requested_document_id
    and document.status = 'emitida'
  for update;

  if previous_token is null then
    raise exception 'Receita emitida nao encontrada';
  end if;

  update public.clinical_prescription_documents document
  set
    share_token = generated_token,
    share_enabled = true,
    reissue_count = coalesce(document.reissue_count, 0) + 1,
    last_reissued_at = now(),
    updated_at = now()
  where document.id = requested_document_id
  returning
    document.share_token,
    document.reissue_count,
    document.last_reissued_at
  into
    share_token,
    reissue_count,
    last_reissued_at;

  insert into public.clinical_prescription_reissues (
    prescription_document_id,
    previous_share_token,
    new_share_token,
    reason,
    reissued_by,
    reissued_at
  ) values (
    requested_document_id,
    previous_token,
    generated_token,
    nullif(trim(reissue_reason), ''),
    (select auth.uid()),
    last_reissued_at
  );

  return next;
end;
$$;

revoke all on function public.rotate_prescription_share_token(bigint, text)
from public;
grant execute on function public.rotate_prescription_share_token(bigint, text)
to authenticated;

do $$
begin
  if to_regprocedure('public.log_clinical_change()') is not null then
    drop trigger if exists audit_clinical_changes
    on public.clinical_prescription_reissues;

    create trigger audit_clinical_changes
    after insert or update or delete
    on public.clinical_prescription_reissues
    for each row execute function public.log_clinical_change();
  end if;
end;
$$;

commit;

select
  (
    select count(*)
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'clinical_prescription_reissues'
  ) as prescription_reissue_tables,
  (
    select count(*)
    from information_schema.routines
    where routine_schema = 'public'
      and routine_name = 'rotate_prescription_share_token'
  ) as rotate_token_functions,
  (
    select count(*)
    from public.clinical_prescription_reissues
  ) as prescription_reissues;
