begin;

create table if not exists public.grooming_supplies (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Geral',
  unit text not null default 'unidade',
  current_stock numeric(12, 3) not null default 0 check (current_stock >= 0),
  minimum_stock numeric(12, 3) not null default 0 check (minimum_stock >= 0),
  supplier text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.grooming_supply_movements (
  id bigint generated by default as identity primary key,
  supply_id bigint not null references public.grooming_supplies(id) on delete cascade,
  movement_type text not null check (
    movement_type in (
      'entrada',
      'saida',
      'descarte',
      'vencido',
      'perda',
      'ajuste_positivo',
      'ajuste_negativo'
    )
  ),
  quantity numeric(12, 3) not null check (quantity > 0),
  unit_cost numeric(10, 2) not null default 0 check (unit_cost >= 0),
  total_cost numeric(10, 2) generated always as (round((quantity * unit_cost)::numeric, 2)) stored,
  supplier text,
  movement_date date not null default current_date,
  expiration_date date,
  payment_status text not null default 'Pago' check (payment_status in ('Pago', 'Pendente')),
  payment_method text,
  due_date date,
  financial_entry_id bigint references public.financial_entries(id) on delete set null,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.groomer_daily_payments (
  id bigint generated by default as identity primary key,
  professional_name text not null,
  work_date date not null default current_date,
  payment_type text not null default 'diaria' check (
    payment_type in ('diaria', 'comissao', 'extra')
  ),
  amount numeric(10, 2) not null check (amount >= 0),
  payment_status text not null default 'Pendente' check (payment_status in ('Pago', 'Pendente')),
  payment_method text,
  due_date date,
  financial_entry_id bigint references public.financial_entries(id) on delete set null,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_grooming_supplies_name
on public.grooming_supplies(name);

create index if not exists idx_grooming_supplies_category
on public.grooming_supplies(category);

create index if not exists idx_grooming_supply_movements_supply_id
on public.grooming_supply_movements(supply_id);

create index if not exists idx_grooming_supply_movements_expiration_date
on public.grooming_supply_movements(expiration_date);

create index if not exists idx_grooming_supply_movements_due_date
on public.grooming_supply_movements(due_date);

create index if not exists idx_groomer_daily_payments_work_date
on public.groomer_daily_payments(work_date);

create index if not exists idx_groomer_daily_payments_due_date
on public.groomer_daily_payments(due_date);

create or replace function public.get_grooming_supply_stock_delta(
  selected_movement_type text,
  selected_quantity numeric
)
returns numeric
language sql
immutable
as $$
  select case
    when selected_movement_type in ('entrada', 'ajuste_positivo') then coalesce(selected_quantity, 0)
    when selected_movement_type in (
      'saida',
      'descarte',
      'vencido',
      'perda',
      'ajuste_negativo'
    ) then -coalesce(selected_quantity, 0)
    else 0
  end;
$$;

create or replace function public.sync_grooming_supply_stock()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_delta numeric;
  new_delta numeric;
begin
  if tg_op = 'INSERT' then
    new_delta := public.get_grooming_supply_stock_delta(
      new.movement_type,
      new.quantity
    );

    update public.grooming_supplies
    set
      current_stock = current_stock + new_delta,
      updated_at = now()
    where id = new.supply_id;

    return new;
  end if;

  if tg_op = 'UPDATE' then
    old_delta := public.get_grooming_supply_stock_delta(
      old.movement_type,
      old.quantity
    );

    new_delta := public.get_grooming_supply_stock_delta(
      new.movement_type,
      new.quantity
    );

    if old.supply_id = new.supply_id then
      update public.grooming_supplies
      set
        current_stock = current_stock - old_delta + new_delta,
        updated_at = now()
      where id = new.supply_id;
    else
      update public.grooming_supplies
      set
        current_stock = current_stock - old_delta,
        updated_at = now()
      where id = old.supply_id;

      update public.grooming_supplies
      set
        current_stock = current_stock + new_delta,
        updated_at = now()
      where id = new.supply_id;
    end if;

    return new;
  end if;

  if tg_op = 'DELETE' then
    old_delta := public.get_grooming_supply_stock_delta(
      old.movement_type,
      old.quantity
    );

    update public.grooming_supplies
    set
      current_stock = current_stock - old_delta,
      updated_at = now()
    where id = old.supply_id;

    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists grooming_supply_stock_sync
on public.grooming_supply_movements;

create trigger grooming_supply_stock_sync
after insert or update or delete
on public.grooming_supply_movements
for each row
execute function public.sync_grooming_supply_stock();

alter table public.grooming_supplies enable row level security;
alter table public.grooming_supply_movements enable row level security;
alter table public.groomer_daily_payments enable row level security;

drop policy if exists "Grooming users can read supplies"
on public.grooming_supplies;

create policy "Grooming users can read supplies"
on public.grooming_supplies for select to authenticated
using (
  public.current_user_can_access('servicos')
  or public.current_user_can_access('financeiro')
  or public.current_user_can_access('dashboard')
);

drop policy if exists "Grooming users can manage supplies"
on public.grooming_supplies;

create policy "Grooming users can manage supplies"
on public.grooming_supplies for all to authenticated
using (
  public.current_user_can_access('servicos')
  or public.current_user_can_access('financeiro')
)
with check (
  public.current_user_can_access('servicos')
  or public.current_user_can_access('financeiro')
);

drop policy if exists "Grooming users can read supply movements"
on public.grooming_supply_movements;

create policy "Grooming users can read supply movements"
on public.grooming_supply_movements for select to authenticated
using (
  public.current_user_can_access('servicos')
  or public.current_user_can_access('financeiro')
  or public.current_user_can_access('dashboard')
);

drop policy if exists "Grooming users can manage supply movements"
on public.grooming_supply_movements;

create policy "Grooming users can manage supply movements"
on public.grooming_supply_movements for all to authenticated
using (
  public.current_user_can_access('servicos')
  or public.current_user_can_access('financeiro')
)
with check (
  public.current_user_can_access('servicos')
  or public.current_user_can_access('financeiro')
);

drop policy if exists "Finance users can read groomer payments"
on public.groomer_daily_payments;

create policy "Finance users can read groomer payments"
on public.groomer_daily_payments for select to authenticated
using (
  public.current_user_can_access('financeiro')
  or public.current_user_can_access('dashboard')
);

drop policy if exists "Finance users can manage groomer payments"
on public.groomer_daily_payments;

create policy "Finance users can manage groomer payments"
on public.groomer_daily_payments for all to authenticated
using (public.current_user_can_access('financeiro'))
with check (public.current_user_can_access('financeiro'));

grant select, insert, update, delete
on public.grooming_supplies,
   public.grooming_supply_movements,
   public.groomer_daily_payments
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

commit;

select
  (
    select count(*)
    from information_schema.tables
    where table_schema = 'public'
      and table_name in (
        'grooming_supplies',
        'grooming_supply_movements',
        'groomer_daily_payments'
      )
  ) as grooming_tables,
  (
    select count(*)
    from information_schema.routines
    where specific_schema = 'public'
      and routine_name in (
        'get_grooming_supply_stock_delta',
        'sync_grooming_supply_stock'
      )
  ) as stock_functions,
  (
    select count(*)
    from information_schema.triggers
    where event_object_schema = 'public'
      and event_object_table = 'grooming_supply_movements'
      and trigger_name = 'grooming_supply_stock_sync'
  ) as stock_triggers;
