-- 032_pos_cash_register.sql
-- Controle de caixa do PDV: abertura, suprimento, sangria e fechamento.

begin;

create table if not exists public.pos_cash_registers (
  id bigint generated by default as identity primary key,
  opened_by uuid references public.user_profiles(id) on delete set null,
  opening_amount numeric(12, 2) not null default 0 check (opening_amount >= 0),
  expected_amount numeric(12, 2) not null default 0,
  closing_amount numeric(12, 2),
  difference_amount numeric(12, 2),
  status text not null default 'Aberto'
    check (status in ('Aberto', 'Fechado')),
  notes text,
  opened_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.pos_cash_movements (
  id bigint generated by default as identity primary key,
  cash_register_id bigint not null
    references public.pos_cash_registers(id) on delete cascade,
  movement_type text not null
    check (movement_type in ('abertura', 'suprimento', 'sangria', 'fechamento')),
  amount numeric(12, 2) not null check (amount >= 0),
  notes text,
  created_by uuid references public.user_profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create unique index if not exists pos_cash_registers_single_open_idx
on public.pos_cash_registers ((status))
where status = 'Aberto';

create index if not exists idx_pos_cash_registers_opened_at
on public.pos_cash_registers(opened_at desc);

create index if not exists idx_pos_cash_movements_register_id
on public.pos_cash_movements(cash_register_id, created_at);

alter table public.pos_cash_registers enable row level security;
alter table public.pos_cash_movements enable row level security;

drop policy if exists "PDV users can read cash registers" on public.pos_cash_registers;
create policy "PDV users can read cash registers"
on public.pos_cash_registers
for select
to authenticated
using (public.current_user_can_access('pdv'));

drop policy if exists "PDV users can read cash movements" on public.pos_cash_movements;
create policy "PDV users can read cash movements"
on public.pos_cash_movements
for select
to authenticated
using (public.current_user_can_access('pdv'));

grant select on public.pos_cash_registers to authenticated;
grant select on public.pos_cash_movements to authenticated;
grant usage, select on sequence public.pos_cash_registers_id_seq to authenticated;
grant usage, select on sequence public.pos_cash_movements_id_seq to authenticated;

create or replace function public.recalculate_pos_cash_expected(
  selected_register_id bigint
)
returns numeric
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(register.opening_amount, 0)
    + coalesce(sum(
      case
        when movement.movement_type = 'suprimento' then movement.amount
        when movement.movement_type = 'sangria' then -movement.amount
        else 0
      end
    ), 0)
  from public.pos_cash_registers register
  left join public.pos_cash_movements movement
    on movement.cash_register_id = register.id
  where register.id = selected_register_id
  group by register.opening_amount;
$$;

create or replace function public.open_pos_cash_register(
  opening_amount numeric,
  notes text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_register_id bigint;
begin
  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao PDV';
  end if;

  if opening_amount < 0 then
    raise exception 'Valor de abertura invalido';
  end if;

  if exists (
    select 1
    from public.pos_cash_registers
    where status = 'Aberto'
  ) then
    raise exception 'Ja existe um caixa aberto';
  end if;

  insert into public.pos_cash_registers (
    opened_by,
    opening_amount,
    expected_amount,
    notes
  )
  values (
    (select auth.uid()),
    opening_amount,
    opening_amount,
    nullif(trim(notes), '')
  )
  returning id into new_register_id;

  insert into public.pos_cash_movements (
    cash_register_id,
    movement_type,
    amount,
    notes,
    created_by
  )
  values (
    new_register_id,
    'abertura',
    opening_amount,
    nullif(trim(notes), ''),
    (select auth.uid())
  );

  return new_register_id;
end;
$$;

create or replace function public.add_pos_cash_movement(
  selected_register_id bigint,
  selected_movement_type text,
  selected_amount numeric,
  notes text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_movement_id bigint;
  new_expected_amount numeric(12, 2);
begin
  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao PDV';
  end if;

  if selected_movement_type not in ('suprimento', 'sangria') then
    raise exception 'Tipo de movimentacao invalido';
  end if;

  if selected_amount <= 0 then
    raise exception 'Valor da movimentacao deve ser maior que zero';
  end if;

  if not exists (
    select 1
    from public.pos_cash_registers
    where id = selected_register_id
      and status = 'Aberto'
  ) then
    raise exception 'Caixa aberto nao encontrado';
  end if;

  insert into public.pos_cash_movements (
    cash_register_id,
    movement_type,
    amount,
    notes,
    created_by
  )
  values (
    selected_register_id,
    selected_movement_type,
    selected_amount,
    nullif(trim(notes), ''),
    (select auth.uid())
  )
  returning id into new_movement_id;

  new_expected_amount := public.recalculate_pos_cash_expected(
    selected_register_id
  );

  update public.pos_cash_registers
  set expected_amount = new_expected_amount
  where id = selected_register_id;

  return new_movement_id;
end;
$$;

create or replace function public.close_pos_cash_register(
  selected_register_id bigint,
  selected_closing_amount numeric,
  selected_notes text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  new_expected_amount numeric(12, 2);
begin
  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao PDV';
  end if;

  if selected_closing_amount < 0 then
    raise exception 'Valor de fechamento invalido';
  end if;

  if not exists (
    select 1
    from public.pos_cash_registers
    where id = selected_register_id
      and status = 'Aberto'
  ) then
    raise exception 'Caixa aberto nao encontrado';
  end if;

  new_expected_amount := public.recalculate_pos_cash_expected(
    selected_register_id
  );

  insert into public.pos_cash_movements (
    cash_register_id,
    movement_type,
    amount,
    notes,
    created_by
  )
  values (
    selected_register_id,
    'fechamento',
    selected_closing_amount,
    nullif(trim(selected_notes), ''),
    (select auth.uid())
  );

  update public.pos_cash_registers
  set
    expected_amount = new_expected_amount,
    closing_amount = selected_closing_amount,
    difference_amount = selected_closing_amount - new_expected_amount,
    status = 'Fechado',
    closed_at = now(),
    notes = coalesce(nullif(trim(selected_notes), ''), notes)
  where id = selected_register_id;
end;
$$;

revoke execute on function public.recalculate_pos_cash_expected(bigint)
from public, anon;
grant execute on function public.recalculate_pos_cash_expected(bigint)
to authenticated;

revoke execute on function public.open_pos_cash_register(numeric, text)
from public, anon;
grant execute on function public.open_pos_cash_register(numeric, text)
to authenticated;

revoke execute on function public.add_pos_cash_movement(bigint, text, numeric, text)
from public, anon;
grant execute on function public.add_pos_cash_movement(bigint, text, numeric, text)
to authenticated;

revoke execute on function public.close_pos_cash_register(bigint, numeric, text)
from public, anon;
grant execute on function public.close_pos_cash_register(bigint, numeric, text)
to authenticated;

commit;
