-- 034_pos_split_payments.sql
-- Registra pagamentos divididos em vendas do PDV.

begin;

create table if not exists public.pos_sale_payments (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.pos_sales(id) on delete cascade,
  payment_method text not null,
  amount numeric(12, 2) not null check (amount > 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_pos_sale_payments_sale_id
on public.pos_sale_payments(sale_id);

alter table public.pos_sale_payments enable row level security;

drop policy if exists "PDV users can read sale payments" on public.pos_sale_payments;
create policy "PDV users can read sale payments"
on public.pos_sale_payments
for select
to authenticated
using (public.current_user_can_access('pdv'));

grant select on public.pos_sale_payments to authenticated;
grant usage, select on sequence public.pos_sale_payments_id_seq to authenticated;

create or replace function public.create_pos_sale_with_payments(
  customer_tutor_id bigint,
  customer_name text,
  items jsonb,
  payments jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_sale_id bigint;
  payment_item jsonb;
  payment_method text;
  payment_amount numeric(12, 2);
  payment_total numeric(12, 2) := 0;
  payment_summary text;
  sale_total numeric(12, 2);
begin
  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao PDV';
  end if;

  if payments is null
    or jsonb_typeof(payments) <> 'array'
    or jsonb_array_length(payments) = 0
  then
    raise exception 'Informe ao menos uma forma de pagamento';
  end if;

  for payment_item in select * from jsonb_array_elements(payments)
  loop
    payment_method := nullif(trim(payment_item ->> 'payment_method'), '');
    payment_amount := (payment_item ->> 'amount')::numeric;

    if payment_method is null then
      raise exception 'Forma de pagamento invalida';
    end if;

    if payment_amount <= 0 then
      raise exception 'Valor de pagamento deve ser maior que zero';
    end if;

    payment_total := payment_total + payment_amount;
  end loop;

  select string_agg(
    format(
      '%s: R$ %s',
      nullif(trim(item ->> 'payment_method'), ''),
      replace(to_char((item ->> 'amount')::numeric, 'FM999999990.00'), '.', ',')
    ),
    ' + '
  )
  into payment_summary
  from jsonb_array_elements(payments) as item;

  new_sale_id := public.create_pos_sale(
    customer_tutor_id,
    customer_name,
    coalesce(payment_summary, 'Pagamento dividido'),
    items
  );

  select total into sale_total
  from public.pos_sales
  where id = new_sale_id;

  if round(payment_total, 2) <> round(sale_total, 2) then
    raise exception 'Total dos pagamentos (%) diferente do total da venda (%)',
      payment_total,
      sale_total;
  end if;

  for payment_item in select * from jsonb_array_elements(payments)
  loop
    insert into public.pos_sale_payments (
      sale_id,
      payment_method,
      amount
    )
    values (
      new_sale_id,
      nullif(trim(payment_item ->> 'payment_method'), ''),
      (payment_item ->> 'amount')::numeric
    );
  end loop;

  update public.financial_entries
  set forma_pagamento = coalesce(payment_summary, forma_pagamento)
  where descricao like format('Venda PDV #%s - %%', new_sale_id);

  return new_sale_id;
end;
$$;

revoke execute on function public.create_pos_sale_with_payments(
  bigint,
  text,
  jsonb,
  jsonb
) from public, anon;

grant execute on function public.create_pos_sale_with_payments(
  bigint,
  text,
  jsonb,
  jsonb
) to authenticated;

commit;
