begin;

create table if not exists public.grooming_equipment (
  id bigint generated by default as identity primary key,
  name text not null,
  equipment_type text not null default 'Outro' check (
    equipment_type in ('Secador', 'Lâmina', 'Máquina', 'Tesoura', 'Outro')
  ),
  size_or_model text,
  serial_number text,
  supplier text,
  purchase_date date,
  purchase_cost numeric(10, 2) check (purchase_cost is null or purchase_cost >= 0),
  status text not null default 'Em uso' check (
    status in ('Em uso', 'Em manutenção', 'Enviado para afiação', 'Baixado')
  ),
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.grooming_equipment_services (
  id bigint generated by default as identity primary key,
  equipment_id bigint not null references public.grooming_equipment(id) on delete cascade,
  service_type text not null default 'Manutenção' check (
    service_type in ('Afiação', 'Manutenção', 'Conserto', 'Limpeza', 'Outro')
  ),
  supplier text,
  sent_date date not null default current_date,
  expected_return_date date,
  returned_date date,
  cost numeric(10, 2) not null default 0 check (cost >= 0),
  payment_status text not null default 'Pendente' check (payment_status in ('Pago', 'Pendente')),
  payment_method text,
  due_date date,
  notes text,
  financial_entry_id bigint references public.financial_entries(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_grooming_equipment_type
on public.grooming_equipment(equipment_type);

create index if not exists idx_grooming_equipment_status
on public.grooming_equipment(status);

create index if not exists idx_grooming_equipment_services_equipment_id
on public.grooming_equipment_services(equipment_id);

create index if not exists idx_grooming_equipment_services_supplier
on public.grooming_equipment_services(supplier);

alter table public.grooming_equipment enable row level security;
alter table public.grooming_equipment_services enable row level security;

drop policy if exists "Grooming users can read equipment"
on public.grooming_equipment;

create policy "Grooming users can read equipment"
on public.grooming_equipment for select to authenticated
using (
  public.current_user_can_access('servicos')
  or public.current_user_can_access('financeiro')
  or public.current_user_can_access('dashboard')
);

drop policy if exists "Grooming users can manage equipment"
on public.grooming_equipment;

create policy "Grooming users can manage equipment"
on public.grooming_equipment for all to authenticated
using (public.current_user_can_access('servicos'))
with check (public.current_user_can_access('servicos'));

drop policy if exists "Grooming users can read equipment services"
on public.grooming_equipment_services;

create policy "Grooming users can read equipment services"
on public.grooming_equipment_services for select to authenticated
using (
  public.current_user_can_access('servicos')
  or public.current_user_can_access('financeiro')
  or public.current_user_can_access('dashboard')
);

drop policy if exists "Grooming users can manage equipment services"
on public.grooming_equipment_services;

create policy "Grooming users can manage equipment services"
on public.grooming_equipment_services for all to authenticated
using (public.current_user_can_access('servicos'))
with check (public.current_user_can_access('servicos'));

grant select, insert, update, delete
on public.grooming_equipment,
   public.grooming_equipment_services
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Service users can insert grooming financial entries"
on public.financial_entries;

create policy "Service users can insert grooming financial entries"
on public.financial_entries
for insert
to authenticated
with check (
  public.current_user_can_access('servicos')
  and tipo = 'Despesa'
  and status_pagamento = 'Pendente'
  and origem in (
    'grooming_supply',
    'groomer_daily_payment',
    'grooming_equipment_service'
  )
);

drop policy if exists "Service users can read grooming financial entries"
on public.financial_entries;

create policy "Service users can read grooming financial entries"
on public.financial_entries
for select
to authenticated
using (
  public.current_user_can_access('servicos')
  and origem in (
    'grooming_supply',
    'groomer_daily_payment',
    'grooming_equipment_service'
  )
);

commit;
