-- Modelos administráveis para documentos clínicos.

begin;

create table if not exists public.clinical_document_templates (
  id bigint generated by default as identity primary key,
  document_type text not null check (
    document_type in ('Atestado', 'Declaração', 'Orientação')
  ),
  title text not null,
  content text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references public.user_profiles(id) on delete set null
    default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clinical_document_templates_title_unique unique (title)
);

create index if not exists idx_clinical_document_templates_active_order
on public.clinical_document_templates(active, sort_order, title);

alter table public.clinical_document_templates enable row level security;

drop policy if exists "Clinic users can read document templates"
on public.clinical_document_templates;
create policy "Clinic users can read document templates"
on public.clinical_document_templates
for select
to authenticated
using (public.current_user_can_access('clinica'));

drop policy if exists "Clinic users can manage document templates"
on public.clinical_document_templates;
create policy "Clinic users can manage document templates"
on public.clinical_document_templates
for all
to authenticated
using (public.current_user_can_access('clinica'))
with check (public.current_user_can_access('clinica'));

grant select, insert, update, delete
on public.clinical_document_templates to authenticated;
grant usage, select on sequence public.clinical_document_templates_id_seq
to authenticated;

insert into public.clinical_document_templates (
  document_type,
  title,
  content,
  sort_order
)
values
  ('Atestado', 'Atestado de saúde animal', E'Atesto, para os devidos fins, que o paciente {pet}, sob responsabilidade de {tutor}, foi avaliado nesta data.\n\nCondição clínica e observações:\n', 10),
  ('Declaração', 'Declaração de comparecimento', 'Declaro que {tutor} compareceu à Clínica Veterinária Pet Maia nesta data, acompanhando o paciente {pet}, para atendimento veterinário.', 20),
  ('Declaração', 'Autorização para procedimento', E'Eu, {tutor}, responsável pelo paciente {pet}, autorizo a realização do procedimento descrito abaixo, após receber esclarecimentos sobre benefícios, riscos e cuidados.\n\nProcedimento autorizado:\n', 30),
  ('Declaração', 'Autorização anestésica e cirúrgica', E'Eu, {tutor}, responsável pelo paciente {pet}, autorizo o procedimento anestésico e/ou cirúrgico indicado, declarando ter recebido esclarecimentos sobre riscos, exames e cuidados necessários.\n\nProcedimento:\n', 40),
  ('Declaração', 'Termo de recusa de tratamento', E'Eu, {tutor}, responsável pelo paciente {pet}, declaro que fui informado sobre a recomendação clínica descrita abaixo e, neste momento, opto por não autorizar sua realização.\n\nRecomendação recusada:\n', 50),
  ('Orientação', 'Orientações ao responsável', E'Paciente: {pet}\nResponsável: {tutor}\n\nOrientações e cuidados:\n', 60)
on conflict (title) do nothing;

commit;
