-- 044_product_stock_control.sql
-- Historico de estoque, inventario fisico e controle de lotes/validade.

begin;

create table if not exists public.product_stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  movement_kind text not null default 'sistema'
    check (movement_kind in ('entrada', 'saida', 'inventario', 'perda', 'vencido', 'sistema', 'edicao')),
  quantity_delta integer not null check (quantity_delta <> 0),
  previous_stock integer not null check (previous_stock >= 0),
  resulting_stock integer not null check (resulting_stock >= 0),
  reason text not null,
  batch_number text,
  expiration_date date,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.product_batches (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  batch_number text not null,
  expiration_date date,
  quantity integer not null default 0 check (quantity >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, batch_number)
);

create index if not exists idx_product_stock_movements_product_created
on public.product_stock_movements(product_id, created_at desc);

create index if not exists idx_product_stock_movements_created
on public.product_stock_movements(created_at desc);

create index if not exists idx_product_batches_expiration_active
on public.product_batches(expiration_date)
where active = true and quantity > 0;

alter table public.product_stock_movements enable row level security;
alter table public.product_batches enable row level security;

drop policy if exists "PDV users can read stock movements" on public.product_stock_movements;
create policy "PDV users can read stock movements"
on public.product_stock_movements for select to authenticated
using (public.current_user_can_access('pdv'));

drop policy if exists "PDV users can read product batches" on public.product_batches;
create policy "PDV users can read product batches"
on public.product_batches for select to authenticated
using (public.current_user_can_access('pdv'));

revoke all on public.product_stock_movements from anon, authenticated;
revoke all on public.product_batches from anon, authenticated;
grant select on public.product_stock_movements to authenticated;
grant select on public.product_batches to authenticated;

create or replace function public.record_product_stock_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  configured_kind text := nullif(current_setting('pet_maia.stock_kind', true), '');
  configured_reason text := nullif(current_setting('pet_maia.stock_reason', true), '');
  configured_batch text := nullif(current_setting('pet_maia.stock_batch', true), '');
  configured_expiration text := nullif(current_setting('pet_maia.stock_expiration', true), '');
begin
  if new.estoque is distinct from old.estoque then
    insert into public.product_stock_movements (
      product_id,
      movement_kind,
      quantity_delta,
      previous_stock,
      resulting_stock,
      reason,
      batch_number,
      expiration_date,
      created_by
    ) values (
      new.id,
      case
        when configured_kind in ('entrada', 'saida', 'inventario', 'perda', 'vencido', 'sistema', 'edicao')
          then configured_kind
        else 'sistema'
      end,
      new.estoque - old.estoque,
      old.estoque,
      new.estoque,
      coalesce(configured_reason, 'Movimentacao automatica do sistema'),
      configured_batch,
      nullif(configured_expiration, '')::date,
      (select auth.uid())
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_record_product_stock_change on public.products;
create trigger trg_record_product_stock_change
after update of estoque on public.products
for each row
execute function public.record_product_stock_change();

create or replace function public.adjust_product_stock(
  selected_product_id bigint,
  selected_quantity_delta integer,
  selected_kind text,
  selected_reason text,
  selected_batch_number text default null,
  selected_expiration_date date default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_product public.products%rowtype;
  normalized_batch text := nullif(btrim(selected_batch_number), '');
  movement_id bigint;
begin
  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao estoque';
  end if;

  if selected_quantity_delta = 0 then
    raise exception 'A quantidade do ajuste deve ser diferente de zero';
  end if;

  if selected_kind not in ('entrada', 'saida', 'inventario', 'perda', 'vencido') then
    raise exception 'Tipo de movimentacao invalido';
  end if;

  if nullif(btrim(selected_reason), '') is null then
    raise exception 'Informe o motivo do ajuste';
  end if;

  select * into selected_product
  from public.products
  where id = selected_product_id
  for update;

  if not found then
    raise exception 'Produto nao encontrado';
  end if;

  if selected_product.estoque + selected_quantity_delta < 0 then
    raise exception 'O ajuste deixaria o estoque negativo';
  end if;

  perform set_config('pet_maia.stock_kind', selected_kind, true);
  perform set_config('pet_maia.stock_reason', btrim(selected_reason), true);
  perform set_config('pet_maia.stock_batch', coalesce(normalized_batch, ''), true);
  perform set_config('pet_maia.stock_expiration', coalesce(selected_expiration_date::text, ''), true);

  update public.products
  set
    estoque = estoque + selected_quantity_delta,
    stock_quantity = estoque + selected_quantity_delta,
    updated_at = now()
  where id = selected_product_id;

  if normalized_batch is not null then
    insert into public.product_batches (
      product_id,
      batch_number,
      expiration_date,
      quantity,
      active
    ) values (
      selected_product_id,
      normalized_batch,
      selected_expiration_date,
      greatest(selected_quantity_delta, 0),
      true
    )
    on conflict (product_id, batch_number) do update
    set
      expiration_date = coalesce(excluded.expiration_date, public.product_batches.expiration_date),
      quantity = greatest(public.product_batches.quantity + selected_quantity_delta, 0),
      active = greatest(public.product_batches.quantity + selected_quantity_delta, 0) > 0,
      updated_at = now();
  end if;

  select id into movement_id
  from public.product_stock_movements
  where product_id = selected_product_id
    and created_by = (select auth.uid())
  order by id desc
  limit 1;

  return movement_id;
end;
$$;

revoke execute on function public.record_product_stock_change() from public, anon, authenticated;
revoke execute on function public.adjust_product_stock(bigint, integer, text, text, text, date) from public, anon;
grant execute on function public.adjust_product_stock(bigint, integer, text, text, text, date) to authenticated;

commit;
