-- 047_pos_stocktake_history.sql
-- Historico auditavel dos balancos fisicos realizados no PDV.

begin;

create table if not exists public.product_stocktakes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  created_by uuid not null references public.user_profiles(id) on delete restrict,
  notes text,
  product_count integer not null check (product_count > 0),
  changed_count integer not null check (changed_count >= 0),
  unchanged_count integer not null check (unchanged_count >= 0),
  total_difference integer not null
);

create table if not exists public.product_stocktake_items (
  id bigint generated by default as identity primary key,
  stocktake_id bigint not null references public.product_stocktakes(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  product_code text,
  previous_quantity integer not null check (previous_quantity >= 0),
  counted_quantity integer not null check (counted_quantity >= 0),
  difference integer not null,
  unique (stocktake_id, product_id)
);

create index if not exists product_stocktakes_created_at_idx
on public.product_stocktakes (created_at desc);

create index if not exists product_stocktake_items_stocktake_id_idx
on public.product_stocktake_items (stocktake_id);

alter table public.product_stocktakes enable row level security;
alter table public.product_stocktake_items enable row level security;

drop policy if exists "PDV users can read stocktakes" on public.product_stocktakes;
create policy "PDV users can read stocktakes"
on public.product_stocktakes for select
to authenticated
using (
  (select auth.uid()) is not null
  and (select public.current_user_can_access('pdv'))
);

drop policy if exists "PDV users can read stocktake items" on public.product_stocktake_items;
create policy "PDV users can read stocktake items"
on public.product_stocktake_items for select
to authenticated
using (
  (select auth.uid()) is not null
  and (select public.current_user_can_access('pdv'))
);

revoke all on public.product_stocktakes from public, anon, authenticated;
revoke all on public.product_stocktake_items from public, anon, authenticated;
grant select on public.product_stocktakes to authenticated;
grant select on public.product_stocktake_items to authenticated;

create or replace function public.complete_product_stocktake(
  items jsonb,
  notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  item jsonb;
  selected_product public.products%rowtype;
  selected_product_id bigint;
  counted_quantity integer;
  v_changed_count integer := 0;
  v_unchanged_count integer := 0;
  v_total_difference integer := 0;
  processed_ids bigint[] := '{}';
  normalized_notes text := nullif(btrim(notes), '');
  stocktake_id bigint;
begin
  if (select auth.uid()) is null then
    raise exception 'Usuario nao autenticado';
  end if;

  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao balanco de estoque';
  end if;

  if jsonb_typeof(items) <> 'array' or jsonb_array_length(items) = 0 then
    raise exception 'Adicione ao menos um produto ao balanco';
  end if;

  insert into public.product_stocktakes (
    created_by, notes, product_count, changed_count, unchanged_count, total_difference
  ) values (
    (select auth.uid()), normalized_notes, jsonb_array_length(items), 0, 0, 0
  )
  returning id into stocktake_id;

  for item in select value from jsonb_array_elements(items)
  loop
    if coalesce(item->>'product_id', '') !~ '^[0-9]+$' then
      raise exception 'Produto invalido no balanco';
    end if;

    if coalesce(item->>'counted_quantity', '') !~ '^[0-9]+$' then
      raise exception 'Quantidade contada invalida';
    end if;

    selected_product_id := (item->>'product_id')::bigint;
    counted_quantity := (item->>'counted_quantity')::integer;

    if selected_product_id = any(processed_ids) then
      raise exception 'Produto duplicado no balanco';
    end if;

    processed_ids := array_append(processed_ids, selected_product_id);

    select * into selected_product
    from public.products
    where id = selected_product_id
      and coalesce(ativo, true) = true
    for update;

    if not found then
      raise exception 'Produto nao encontrado ou inativo: %', selected_product_id;
    end if;

    insert into public.product_stocktake_items (
      stocktake_id,
      product_id,
      product_name,
      product_code,
      previous_quantity,
      counted_quantity,
      difference
    ) values (
      stocktake_id,
      selected_product.id,
      selected_product.nome,
      coalesce(nullif(selected_product.barcode, ''), nullif(selected_product.sku, '')),
      selected_product.estoque,
      counted_quantity,
      counted_quantity - selected_product.estoque
    );

    v_total_difference := v_total_difference + counted_quantity - selected_product.estoque;

    if counted_quantity = selected_product.estoque then
      v_unchanged_count := v_unchanged_count + 1;
      continue;
    end if;

    perform set_config('pet_maia.stock_kind', 'inventario', true);
    perform set_config(
      'pet_maia.stock_reason',
      'Balanco #' || stocktake_id ||
        case when normalized_notes is null then '' else ': ' || normalized_notes end,
      true
    );
    perform set_config('pet_maia.stock_batch', '', true);
    perform set_config('pet_maia.stock_expiration', '', true);

    update public.products
    set estoque = counted_quantity,
        stock_quantity = counted_quantity,
        updated_at = now()
    where id = selected_product_id;

    v_changed_count := v_changed_count + 1;
  end loop;

  update public.product_stocktakes
  set changed_count = v_changed_count,
      unchanged_count = v_unchanged_count,
      total_difference = v_total_difference
  where id = stocktake_id;

  return jsonb_build_object(
    'stocktake_id', stocktake_id,
    'processed_count', jsonb_array_length(items),
    'changed_count', v_changed_count,
    'unchanged_count', v_unchanged_count,
    'total_difference', v_total_difference
  );
end;
$$;

revoke execute on function public.complete_product_stocktake(jsonb, text)
from public, anon;
grant execute on function public.complete_product_stocktake(jsonb, text)
to authenticated;

commit;
