-- 048_pos_stocktake_drafts.sql
-- Rascunho individual de balanco, sem impacto no estoque ate a finalizacao.

begin;

create table if not exists public.product_stocktake_drafts (
  id bigint generated by default as identity primary key,
  created_by uuid not null references public.user_profiles(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (created_by),
  check (jsonb_typeof(items) = 'array')
);

alter table public.product_stocktake_drafts enable row level security;

drop policy if exists "PDV users can read own stocktake draft"
on public.product_stocktake_drafts;
create policy "PDV users can read own stocktake draft"
on public.product_stocktake_drafts for select
to authenticated
using (
  created_by = (select auth.uid())
  and (select public.current_user_can_access('pdv'))
);

drop policy if exists "PDV users can insert own stocktake draft"
on public.product_stocktake_drafts;
create policy "PDV users can insert own stocktake draft"
on public.product_stocktake_drafts for insert
to authenticated
with check (
  created_by = (select auth.uid())
  and (select public.current_user_can_access('pdv'))
);

drop policy if exists "PDV users can update own stocktake draft"
on public.product_stocktake_drafts;
create policy "PDV users can update own stocktake draft"
on public.product_stocktake_drafts for update
to authenticated
using (
  created_by = (select auth.uid())
  and (select public.current_user_can_access('pdv'))
)
with check (
  created_by = (select auth.uid())
  and (select public.current_user_can_access('pdv'))
);

drop policy if exists "PDV users can delete own stocktake draft"
on public.product_stocktake_drafts;
create policy "PDV users can delete own stocktake draft"
on public.product_stocktake_drafts for delete
to authenticated
using (
  created_by = (select auth.uid())
  and (select public.current_user_can_access('pdv'))
);

revoke all on public.product_stocktake_drafts from public, anon, authenticated;
grant select, insert, update, delete on public.product_stocktake_drafts
to authenticated;
grant usage, select on sequence public.product_stocktake_drafts_id_seq
to authenticated;

create or replace function public.save_product_stocktake_draft(
  draft_items jsonb,
  draft_notes text default null
)
returns public.product_stocktake_drafts
language plpgsql
security invoker
set search_path = ''
as $$
declare
  saved_draft public.product_stocktake_drafts%rowtype;
begin
  if (select auth.uid()) is null then
    raise exception 'Usuario nao autenticado';
  end if;

  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao rascunho do balanco';
  end if;

  if jsonb_typeof(draft_items) <> 'array' or jsonb_array_length(draft_items) = 0 then
    raise exception 'Adicione ao menos um produto ao rascunho';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(draft_items) as draft_item
    where coalesce(draft_item->>'product_id', '') !~ '^[0-9]+$'
      or (
        draft_item ? 'counted_quantity'
        and draft_item->>'counted_quantity' is not null
        and draft_item->>'counted_quantity' !~ '^[0-9]+$'
      )
  ) then
    raise exception 'Produto ou quantidade invalida no rascunho';
  end if;

  if (
    select count(*) <> count(distinct (draft_item->>'product_id'))
    from jsonb_array_elements(draft_items) as draft_item
  ) then
    raise exception 'Produto duplicado no rascunho';
  end if;

  insert into public.product_stocktake_drafts (
    created_by, items, notes, updated_at
  ) values (
    (select auth.uid()),
    draft_items,
    nullif(btrim(draft_notes), ''),
    now()
  )
  on conflict (created_by) do update
  set items = excluded.items,
      notes = excluded.notes,
      updated_at = now()
  returning * into saved_draft;

  return saved_draft;
end;
$$;

revoke execute on function public.save_product_stocktake_draft(jsonb, text)
from public, anon;
grant execute on function public.save_product_stocktake_draft(jsonb, text)
to authenticated;

create or replace function public.delete_product_stocktake_draft()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if (select auth.uid()) is null then
    raise exception 'Usuario nao autenticado';
  end if;

  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao rascunho do balanco';
  end if;

  delete from public.product_stocktake_drafts
  where created_by = (select auth.uid());
end;
$$;

revoke execute on function public.delete_product_stocktake_draft()
from public, anon;
grant execute on function public.delete_product_stocktake_draft()
to authenticated;

-- O rascunho e descartado somente dentro da mesma transacao que conclui o balanco.
create or replace function public.complete_product_stocktake(
  items jsonb,
  notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  item jsonb;
  selected_product public.products%rowtype;
  selected_product_id bigint;
  counted_quantity integer;
  v_changed_count integer := 0;
  v_unchanged_count integer := 0;
  v_total_difference integer := 0;
  processed_ids bigint[] := '{}';
  normalized_notes text := nullif(btrim(notes), '');
  stocktake_id bigint;
begin
  if (select auth.uid()) is null then
    raise exception 'Usuario nao autenticado';
  end if;

  if not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao balanco de estoque';
  end if;

  if jsonb_typeof(items) <> 'array' or jsonb_array_length(items) = 0 then
    raise exception 'Adicione ao menos um produto ao balanco';
  end if;

  insert into public.product_stocktakes (
    created_by, notes, product_count, changed_count, unchanged_count, total_difference
  ) values (
    (select auth.uid()), normalized_notes, jsonb_array_length(items), 0, 0, 0
  ) returning id into stocktake_id;

  for item in select value from jsonb_array_elements(items)
  loop
    if coalesce(item->>'product_id', '') !~ '^[0-9]+$' then
      raise exception 'Produto invalido no balanco';
    end if;
    if coalesce(item->>'counted_quantity', '') !~ '^[0-9]+$' then
      raise exception 'Quantidade contada invalida';
    end if;

    selected_product_id := (item->>'product_id')::bigint;
    counted_quantity := (item->>'counted_quantity')::integer;
    if selected_product_id = any(processed_ids) then
      raise exception 'Produto duplicado no balanco';
    end if;
    processed_ids := array_append(processed_ids, selected_product_id);

    select * into selected_product
    from public.products
    where id = selected_product_id and coalesce(ativo, true) = true
    for update;
    if not found then
      raise exception 'Produto nao encontrado ou inativo: %', selected_product_id;
    end if;

    insert into public.product_stocktake_items (
      stocktake_id, product_id, product_name, product_code,
      previous_quantity, counted_quantity, difference
    ) values (
      stocktake_id, selected_product.id, selected_product.nome,
      coalesce(nullif(selected_product.barcode, ''), nullif(selected_product.sku, '')),
      selected_product.estoque, counted_quantity,
      counted_quantity - selected_product.estoque
    );

    v_total_difference := v_total_difference + counted_quantity - selected_product.estoque;
    if counted_quantity = selected_product.estoque then
      v_unchanged_count := v_unchanged_count + 1;
      continue;
    end if;

    perform set_config('pet_maia.stock_kind', 'inventario', true);
    perform set_config(
      'pet_maia.stock_reason',
      'Balanco #' || stocktake_id ||
        case when normalized_notes is null then '' else ': ' || normalized_notes end,
      true
    );
    perform set_config('pet_maia.stock_batch', '', true);
    perform set_config('pet_maia.stock_expiration', '', true);
    update public.products
    set estoque = counted_quantity,
        stock_quantity = counted_quantity,
        updated_at = now()
    where id = selected_product_id;
    v_changed_count := v_changed_count + 1;
  end loop;

  update public.product_stocktakes
  set changed_count = v_changed_count,
      unchanged_count = v_unchanged_count,
      total_difference = v_total_difference
  where id = stocktake_id;

  delete from public.product_stocktake_drafts
  where created_by = (select auth.uid());

  return jsonb_build_object(
    'stocktake_id', stocktake_id,
    'processed_count', jsonb_array_length(items),
    'changed_count', v_changed_count,
    'unchanged_count', v_unchanged_count,
    'total_difference', v_total_difference
  );
end;
$$;

revoke execute on function public.complete_product_stocktake(jsonb, text)
from public, anon;
grant execute on function public.complete_product_stocktake(jsonb, text)
to authenticated;

commit;
