create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete restrict,
  expected_date date,
  status text not null default 'Rascunho'
    check (status in ('Rascunho','Enviado','Recebido parcialmente','Concluído','Cancelado')),
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchase_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.purchase_orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  ordered_quantity integer not null check (ordered_quantity > 0),
  received_quantity integer not null default 0 check (received_quantity >= 0 and received_quantity <= ordered_quantity),
  unit_cost numeric(12,2) not null default 0 check (unit_cost >= 0),
  unique (order_id, product_id)
);

create index if not exists idx_purchase_orders_status_created on public.purchase_orders(status, created_at desc);
create index if not exists idx_purchase_order_items_order on public.purchase_order_items(order_id);
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;

create policy "PDV users can read purchase orders" on public.purchase_orders
for select to authenticated using (public.current_user_can_access('pdv'));
create policy "PDV users can read purchase order items" on public.purchase_order_items
for select to authenticated using (public.current_user_can_access('pdv'));

revoke all on public.purchase_orders, public.purchase_order_items from anon, authenticated;
grant select on public.purchase_orders, public.purchase_order_items to authenticated;

create or replace function public.create_purchase_order(
  selected_supplier_id bigint, selected_expected_date date, selected_notes text, items jsonb
) returns bigint language plpgsql security definer set search_path='' as $$
declare new_order_id bigint; item jsonb; product_exists boolean;
begin
  if not public.current_user_can_access('pdv') then raise exception 'Acesso negado ao PDV'; end if;
  if not exists(select 1 from public.suppliers where id=selected_supplier_id and ativo=true) then raise exception 'Fornecedor inválido'; end if;
  if items is null or jsonb_typeof(items)<>'array' or jsonb_array_length(items)=0 then raise exception 'Informe os produtos do pedido'; end if;
  insert into public.purchase_orders(supplier_id,expected_date,notes) values(selected_supplier_id,selected_expected_date,nullif(trim(selected_notes),'')) returning id into new_order_id;
  for item in select * from jsonb_array_elements(items) loop
    select exists(select 1 from public.products where id=(item->>'product_id')::bigint and ativo=true) into product_exists;
    if not product_exists or (item->>'quantidade')::integer<=0 or (item->>'custo_unitario')::numeric<0 then raise exception 'Item inválido'; end if;
    insert into public.purchase_order_items(order_id,product_id,ordered_quantity,unit_cost)
    values(new_order_id,(item->>'product_id')::bigint,(item->>'quantidade')::integer,(item->>'custo_unitario')::numeric);
  end loop;
  return new_order_id;
end; $$;

create or replace function public.set_purchase_order_status(selected_order_id bigint, selected_status text)
returns void language plpgsql security definer set search_path='' as $$
declare current_status text;
begin
  if not public.current_user_can_access('pdv') then raise exception 'Acesso negado ao PDV'; end if;
  select status into current_status from public.purchase_orders where id=selected_order_id for update;
  if not found then raise exception 'Pedido não encontrado'; end if;
  if selected_status='Enviado' and current_status='Rascunho' then
    update public.purchase_orders set status='Enviado',updated_at=now() where id=selected_order_id;
  elsif selected_status='Cancelado' and current_status in ('Rascunho','Enviado') then
    update public.purchase_orders set status='Cancelado',updated_at=now() where id=selected_order_id;
  else raise exception 'Mudança de status não permitida'; end if;
end; $$;

create or replace function public.receive_purchase_order(selected_order_id bigint, receipts jsonb)
returns void language plpgsql security definer set search_path='' as $$
declare selected_order public.purchase_orders%rowtype; receipt jsonb; selected_item public.purchase_order_items%rowtype; receive_qty integer; pending_count integer;
begin
  if not public.current_user_can_access('pdv') then raise exception 'Acesso negado ao PDV'; end if;
  select * into selected_order from public.purchase_orders where id=selected_order_id for update;
  if not found or selected_order.status in ('Concluído','Cancelado') then raise exception 'Pedido não disponível para recebimento'; end if;
  if receipts is null or jsonb_typeof(receipts)<>'array' or jsonb_array_length(receipts)=0 then raise exception 'Informe as quantidades recebidas'; end if;
  for receipt in select * from jsonb_array_elements(receipts) loop
    select * into selected_item from public.purchase_order_items where id=(receipt->>'item_id')::bigint and order_id=selected_order_id for update;
    receive_qty := (receipt->>'quantidade')::integer;
    if not found or receive_qty<=0 or selected_item.received_quantity+receive_qty>selected_item.ordered_quantity then raise exception 'Quantidade recebida inválida'; end if;
    update public.purchase_order_items set received_quantity=received_quantity+receive_qty where id=selected_item.id;
    perform set_config('pet_maia.stock_kind','entrada',true);
    perform set_config('pet_maia.stock_reason','Recebimento do pedido de compra #'||selected_order_id,true);
    update public.products set estoque=estoque+receive_qty,stock_quantity=estoque+receive_qty,preco_custo=selected_item.unit_cost,updated_at=now() where id=selected_item.product_id;
  end loop;
  select count(*) into pending_count from public.purchase_order_items where order_id=selected_order_id and received_quantity<ordered_quantity;
  update public.purchase_orders set status=case when pending_count=0 then 'Concluído' else 'Recebido parcialmente' end,updated_at=now() where id=selected_order_id;
end; $$;

revoke execute on function public.create_purchase_order(bigint,date,text,jsonb) from public,anon;
revoke execute on function public.set_purchase_order_status(bigint,text) from public,anon;
revoke execute on function public.receive_purchase_order(bigint,jsonb) from public,anon;
grant execute on function public.create_purchase_order(bigint,date,text,jsonb) to authenticated;
grant execute on function public.set_purchase_order_status(bigint,text) to authenticated;
grant execute on function public.receive_purchase_order(bigint,jsonb) to authenticated;
