create table if not exists public.suspended_pos_sales (
  id bigint generated by default as identity primary key,
  tutor_id bigint references public.tutors(id) on delete set null,
  customer_name text not null default 'Consumidor',
  notes text,
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.suspended_pos_sale_items (
  id bigint generated by default as identity primary key,
  suspended_sale_id bigint not null references public.suspended_pos_sales(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  unique (suspended_sale_id, product_id)
);

create index if not exists suspended_pos_sales_created_at_idx on public.suspended_pos_sales(created_at desc);
create index if not exists suspended_pos_sale_items_sale_idx on public.suspended_pos_sale_items(suspended_sale_id);

alter table public.suspended_pos_sales enable row level security;
alter table public.suspended_pos_sale_items enable row level security;

drop policy if exists suspended_pos_sales_select on public.suspended_pos_sales;
create policy suspended_pos_sales_select on public.suspended_pos_sales for select to authenticated
using (public.current_user_can_access('pdv'));

create policy suspended_pos_sales_insert on public.suspended_pos_sales for insert to authenticated
with check (public.current_user_can_access('pdv') and created_by = auth.uid());

create policy suspended_pos_sales_delete on public.suspended_pos_sales for delete to authenticated
using (public.current_user_can_access('pdv'));

drop policy if exists suspended_pos_sale_items_select on public.suspended_pos_sale_items;
create policy suspended_pos_sale_items_select on public.suspended_pos_sale_items for select to authenticated
using (public.current_user_can_access('pdv'));

create policy suspended_pos_sale_items_insert on public.suspended_pos_sale_items for insert to authenticated
with check (public.current_user_can_access('pdv') and exists (select 1 from public.suspended_pos_sales sale where sale.id = suspended_sale_id and sale.created_by = auth.uid()));

revoke all on public.suspended_pos_sales, public.suspended_pos_sale_items from anon, authenticated;
grant select, insert, delete on public.suspended_pos_sales to authenticated;
grant select, insert on public.suspended_pos_sale_items to authenticated;
grant usage, select on sequence public.suspended_pos_sales_id_seq, public.suspended_pos_sale_items_id_seq to authenticated;

create or replace function public.suspend_pos_sale(
  selected_tutor_id bigint,
  selected_customer_name text,
  selected_notes text,
  items jsonb
) returns bigint
language plpgsql security invoker set search_path = public, pg_temp as $$
declare
  new_id bigint;
  item jsonb;
  selected_product public.products%rowtype;
begin
  if auth.uid() is null or not public.current_user_can_access('pdv') then raise exception 'Acesso negado'; end if;
  if jsonb_typeof(items) <> 'array' or jsonb_array_length(items) = 0 then raise exception 'Adicione produtos ao carrinho'; end if;

  insert into public.suspended_pos_sales(tutor_id, customer_name, notes, created_by)
  values (selected_tutor_id, coalesce(nullif(trim(selected_customer_name), ''), 'Consumidor'), nullif(trim(selected_notes), ''), auth.uid())
  returning id into new_id;

  for item in select * from jsonb_array_elements(items) loop
    select * into selected_product from public.products where id = (item->>'product_id')::bigint and ativo = true for share;
    if not found then raise exception 'Produto inválido'; end if;
    if (item->>'quantity')::integer <= 0 or (item->>'quantity')::integer > selected_product.estoque then raise exception 'Quantidade indisponível para %', selected_product.nome; end if;
    insert into public.suspended_pos_sale_items(suspended_sale_id, product_id, quantity, unit_price)
    values (new_id, selected_product.id, (item->>'quantity')::integer, selected_product.preco_venda);
  end loop;
  return new_id;
end;
$$;

create or replace function public.delete_suspended_pos_sale(selected_sale_id bigint) returns void
language plpgsql security invoker set search_path = public, pg_temp as $$
begin
  if auth.uid() is null or not public.current_user_can_access('pdv') then raise exception 'Acesso negado'; end if;
  delete from public.suspended_pos_sales where id = selected_sale_id;
  if not found then raise exception 'Venda suspensa não encontrada'; end if;
end;
$$;

revoke all on function public.suspend_pos_sale(bigint,text,text,jsonb) from public, anon, authenticated;
revoke all on function public.delete_suspended_pos_sale(bigint) from public, anon, authenticated;
grant execute on function public.suspend_pos_sale(bigint,text,text,jsonb) to authenticated;
grant execute on function public.delete_suspended_pos_sale(bigint) to authenticated;
