create table public.pos_sale_returns (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.pos_sales(id) on delete restrict,
  return_type text not null check (return_type in ('Devolução','Troca')),
  amount numeric(12,2) not null check (amount > 0),
  reason text not null,
  created_by uuid not null references public.user_profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);
create table public.pos_sale_return_items (
  id bigint generated by default as identity primary key,
  return_id bigint not null references public.pos_sale_returns(id) on delete cascade,
  sale_item_id bigint not null references public.pos_sale_items(id) on delete restrict,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0)
);
create index on public.pos_sale_returns(sale_id,created_at desc);
create index on public.pos_sale_return_items(return_id);
alter table public.pos_sale_returns enable row level security;
alter table public.pos_sale_return_items enable row level security;
create policy pos_returns_read on public.pos_sale_returns for select to authenticated using (public.current_user_can_access('pdv'));
create policy pos_return_items_read on public.pos_sale_return_items for select to authenticated using (public.current_user_can_access('pdv'));
revoke all on public.pos_sale_returns,public.pos_sale_return_items from anon,authenticated;
grant select on public.pos_sale_returns,public.pos_sale_return_items to authenticated;

create table public.user_notification_history (
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  notification_key text not null,
  title text not null,
  description text not null,
  href text not null,
  read_at timestamptz,
  last_seen_at timestamptz not null default now(),
  primary key(user_id,notification_key)
);
create index on public.user_notification_history(user_id,last_seen_at desc);
alter table public.user_notification_history enable row level security;
create policy notification_own_all on public.user_notification_history for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
revoke all on public.user_notification_history from anon,authenticated;
grant select,insert,update,delete on public.user_notification_history to authenticated;

create table public.financial_recurring_rules (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric(12,2) not null check(amount>0),
  entry_type text not null check(entry_type in ('Receita','Despesa')),
  payment_method text,
  day_of_month integer not null check(day_of_month between 1 and 28),
  start_date date not null,
  end_date date,
  active boolean not null default true,
  created_by uuid not null references public.user_profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  check(end_date is null or end_date>=start_date)
);
alter table public.financial_entries add column if not exists recurring_rule_id bigint references public.financial_recurring_rules(id) on delete set null;
alter table public.financial_entries add column if not exists recurring_period date;
create unique index financial_recurring_period_uidx on public.financial_entries(recurring_rule_id,recurring_period) where recurring_rule_id is not null;
create index on public.financial_recurring_rules(active,start_date,end_date);
alter table public.financial_recurring_rules enable row level security;
create policy recurring_rules_access on public.financial_recurring_rules for all to authenticated using (public.current_user_can_access('financeiro')) with check (public.current_user_can_access('financeiro'));
revoke all on public.financial_recurring_rules from anon,authenticated;
grant select,insert,update,delete on public.financial_recurring_rules to authenticated;
grant usage,select on sequence public.financial_recurring_rules_id_seq to authenticated;

create or replace function public.return_pos_sale(selected_sale_id bigint,selected_type text,selected_reason text,items jsonb) returns bigint
language plpgsql security definer set search_path=public,pg_temp as $$
declare new_return_id bigint; entry jsonb; sale_item public.pos_sale_items%rowtype; qty integer; already_returned integer; total numeric(12,2):=0; open_register bigint;
begin
 if auth.uid() is null or not public.current_user_can_access('pdv') then raise exception 'Acesso negado'; end if;
 if selected_type not in ('Devolução','Troca') or nullif(trim(selected_reason),'') is null then raise exception 'Informe tipo e motivo'; end if;
 if jsonb_typeof(items)<>'array' or jsonb_array_length(items)=0 then raise exception 'Selecione itens'; end if;
 for entry in select * from jsonb_array_elements(items) loop
  select * into sale_item from public.pos_sale_items where id=(entry->>'sale_item_id')::bigint and sale_id=selected_sale_id for update;
  if not found or sale_item.product_id is null then raise exception 'Item inválido'; end if;
  qty:=(entry->>'quantity')::integer;
  select coalesce(sum(ri.quantity),0) into already_returned from public.pos_sale_return_items ri join public.pos_sale_returns r on r.id=ri.return_id where ri.sale_item_id=sale_item.id;
  if qty<=0 or qty+already_returned>sale_item.quantidade then raise exception 'Quantidade de devolução inválida'; end if;
  total:=total+qty*sale_item.valor_unitario;
 end loop;
 insert into public.pos_sale_returns(sale_id,return_type,amount,reason,created_by) values(selected_sale_id,selected_type,total,trim(selected_reason),auth.uid()) returning id into new_return_id;
 for entry in select * from jsonb_array_elements(items) loop
  select * into sale_item from public.pos_sale_items where id=(entry->>'sale_item_id')::bigint;
  qty:=(entry->>'quantity')::integer;
  insert into public.pos_sale_return_items(return_id,sale_item_id,product_id,quantity,unit_price) values(new_return_id,sale_item.id,sale_item.product_id,qty,sale_item.valor_unitario);
  perform set_config('pet_maia.stock_kind','devolucao',true); perform set_config('pet_maia.stock_reason',format('%s da venda #%s',selected_type,selected_sale_id),true);
  update public.products set estoque=estoque+qty,stock_quantity=estoque+qty,updated_at=now() where id=sale_item.product_id;
 end loop;
 if selected_type='Devolução' then
  select id into open_register from public.pos_cash_registers where status='Aberto' order by opened_at desc limit 1 for update;
  if open_register is null then raise exception 'Abra o caixa para registrar o estorno'; end if;
  insert into public.pos_cash_movements(cash_register_id,movement_type,amount,sale_id,notes,created_by) values(open_register,'sangria',total,selected_sale_id,format('Devolução #%s',new_return_id),auth.uid());
  insert into public.financial_entries(descricao,valor,tipo,forma_pagamento,status_pagamento,origem,referencia_id) values(format('Devolução venda PDV #%s',selected_sale_id),total,'Despesa','Dinheiro','Pago','pos_return',new_return_id);
  update public.pos_cash_registers set expected_amount=public.recalculate_pos_cash_expected(open_register) where id=open_register;
 end if;
 return new_return_id;
end; $$;

create or replace function public.generate_recurring_financial_entries(until_date date default current_date) returns integer
language plpgsql security definer set search_path=public,pg_temp as $$
declare rule public.financial_recurring_rules%rowtype; period date; due_date date; generated integer:=0;
begin
 if auth.uid() is null or not public.current_user_can_access('financeiro') then raise exception 'Acesso negado'; end if;
 for rule in select * from public.financial_recurring_rules where active and start_date<=until_date and (end_date is null or end_date>=date_trunc('month',current_date)::date) loop
  period:=date_trunc('month',greatest(rule.start_date,current_date))::date;
  while period<=date_trunc('month',until_date)::date loop
   due_date:=period+(rule.day_of_month-1);
   if due_date>=rule.start_date and (rule.end_date is null or due_date<=rule.end_date) then
    insert into public.financial_entries(descricao,valor,tipo,forma_pagamento,status_pagamento,data_vencimento,origem,recurring_rule_id,recurring_period)
    values(rule.description,rule.amount,rule.entry_type,rule.payment_method,'Pendente',due_date,'recorrente',rule.id,period) on conflict(recurring_rule_id,recurring_period) where recurring_rule_id is not null do nothing;
    if found then generated:=generated+1; end if;
   end if;
   period:=(period+interval '1 month')::date;
  end loop;
 end loop;
 return generated;
end; $$;

revoke all on function public.return_pos_sale(bigint,text,text,jsonb) from public,anon,authenticated;
revoke all on function public.generate_recurring_financial_entries(date) from public,anon,authenticated;
grant execute on function public.return_pos_sale(bigint,text,text,jsonb) to authenticated;
grant execute on function public.generate_recurring_financial_entries(date) to authenticated;
