create table public.clinical_consents (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  clinical_record_id bigint references public.clinical_records(id) on delete set null,
  consent_type text not null check (consent_type in ('Procedimento', 'Anestesia e cirurgia', 'Internação', 'Recusa de tratamento', 'Outro')),
  title text not null,
  content text not null,
  signer_name text not null,
  signer_document text,
  signature_data_url text not null check (signature_data_url like 'data:image/png;base64,%'),
  signed_at timestamptz not null default now(),
  professional_name text not null,
  professional_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index clinical_consents_pet_signed_idx
  on public.clinical_consents (pet_id, signed_at desc);

alter table public.clinical_consents enable row level security;

create policy "Clinic users can manage clinical consents"
on public.clinical_consents
for all
to authenticated
using (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
)
with check (
  public.current_user_can_access('clinica')
  or public.current_user_can_access('pets')
);

revoke all on table public.clinical_consents from anon;
grant select, insert, update, delete on table public.clinical_consents to authenticated, service_role;
grant usage, select on sequence public.clinical_consents_id_seq to authenticated, service_role;
