create table public.clinical_hospitalizations (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  admission_at timestamptz not null default now(),
  discharge_at timestamptz,
  reason text not null,
  veterinarian_name text,
  kennel text,
  status text not null default 'Internado' check (status in ('Internado','Alta')),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.clinical_hospitalization_logs (
  id bigint generated by default as identity primary key,
  hospitalization_id bigint not null references public.clinical_hospitalizations(id) on delete cascade,
  log_type text not null check (log_type in ('Evolução','Sinais vitais','Medicação','Alimentação')),
  notes text not null,
  temperature_c numeric(4,1),
  weight_kg numeric(7,2),
  heart_rate integer,
  respiratory_rate integer,
  professional_name text,
  recorded_at timestamptz not null default now(),
  created_by uuid default auth.uid() references auth.users(id) on delete set null
);

create index clinical_hospitalizations_status_idx on public.clinical_hospitalizations(status, admission_at desc);
create index clinical_hospitalization_logs_parent_idx on public.clinical_hospitalization_logs(hospitalization_id, recorded_at desc);

alter table public.clinical_hospitalizations enable row level security;
alter table public.clinical_hospitalization_logs enable row level security;

create policy "Clinic users can manage hospitalizations" on public.clinical_hospitalizations for all to authenticated
using ((select auth.uid()) is not null and public.current_user_can_access('clinica'))
with check ((select auth.uid()) is not null and public.current_user_can_access('clinica'));

create policy "Clinic users can manage hospitalization logs" on public.clinical_hospitalization_logs for all to authenticated
using ((select auth.uid()) is not null and public.current_user_can_access('clinica'))
with check ((select auth.uid()) is not null and public.current_user_can_access('clinica'));

revoke all on public.clinical_hospitalizations, public.clinical_hospitalization_logs from anon;
grant select, insert, update, delete on public.clinical_hospitalizations, public.clinical_hospitalization_logs to authenticated, service_role;
grant usage, select on sequence public.clinical_hospitalizations_id_seq, public.clinical_hospitalization_logs_id_seq to authenticated, service_role;
