create table public.clinical_tasks (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  task_type text not null check (task_type in (
    'Pós-operatório', 'Exame', 'Curativo', 'Medicação', 'Retorno', 'Outro'
  )),
  title text not null check (length(trim(title)) between 2 and 160),
  due_date date not null,
  priority text not null default 'Normal'
    check (priority in ('Baixa', 'Normal', 'Alta')),
  assigned_to text,
  notes text,
  status text not null default 'Pendente'
    check (status in ('Pendente', 'Concluída')),
  completed_at timestamptz,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index clinical_tasks_due_status_idx
  on public.clinical_tasks (status, due_date, priority);
create index clinical_tasks_pet_idx on public.clinical_tasks (pet_id);

alter table public.clinical_tasks enable row level security;

create policy "Clinic users can manage clinical tasks"
on public.clinical_tasks
for all
to authenticated
using (
  (select auth.uid()) is not null
  and (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  )
)
with check (
  (select auth.uid()) is not null
  and (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  )
);

revoke all on table public.clinical_tasks from anon;
grant select, insert, update, delete on table public.clinical_tasks to authenticated;
grant select, insert, update, delete on table public.clinical_tasks to service_role;
grant usage, select on sequence public.clinical_tasks_id_seq to authenticated;
grant usage, select on sequence public.clinical_tasks_id_seq to service_role;
