create table if not exists public.product_purchase_payments (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.product_purchases(id) on delete cascade,
  financial_entry_id bigint references public.financial_entries(id) on delete set null,
  payment_method text not null check (length(trim(payment_method)) > 0),
  amount numeric(12, 2) not null check (amount > 0),
  due_date date not null,
  created_at timestamptz not null default now()
);

create index if not exists product_purchase_payments_purchase_idx
  on public.product_purchase_payments(purchase_id);

alter table public.product_purchase_payments enable row level security;

drop policy if exists "PDV users can read purchase payments"
  on public.product_purchase_payments;
create policy "PDV users can read purchase payments"
  on public.product_purchase_payments for select to authenticated
  using (public.current_user_can_access('pdv'));

revoke all on public.product_purchase_payments from anon, authenticated;
grant select on public.product_purchase_payments to authenticated;
grant usage, select on sequence public.product_purchase_payments_id_seq
  to authenticated;

create or replace function public.create_product_purchase_split(
  selected_supplier_id bigint,
  document_number text,
  purchase_date date,
  due_date date,
  payments jsonb,
  notes text,
  items jsonb
) returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_purchase_id bigint;
  new_financial_entry_id bigint;
  first_financial_entry_id bigint;
  purchase_total numeric(12, 2) := 0;
  payments_total numeric(12, 2) := 0;
  payment_summary text;
  item jsonb;
  payment jsonb;
  selected_product public.products%rowtype;
  selected_supplier public.suppliers%rowtype;
  item_quantity integer;
  item_cost numeric(12, 2);
  stock_units integer;
  payment_amount numeric(12, 2);
  payment_method text;
begin
  if auth.uid() is null or not public.current_user_can_access('pdv') then
    raise exception 'Acesso negado ao PDV';
  end if;

  select * into selected_supplier
  from public.suppliers
  where id = selected_supplier_id and ativo = true;
  if not found then raise exception 'Fornecedor inválido'; end if;

  if items is null or jsonb_typeof(items) <> 'array'
     or jsonb_array_length(items) = 0 then
    raise exception 'A compra precisa ter ao menos um item';
  end if;

  for item in select * from jsonb_array_elements(items) loop
    select * into selected_product
    from public.products
    where id = (item ->> 'product_id')::bigint
    for update;
    if not found then raise exception 'Produto inválido'; end if;

    item_quantity := (item ->> 'quantidade')::integer;
    item_cost := (item ->> 'custo_unitario')::numeric;
    if item_quantity <= 0 or item_cost < 0 then
      raise exception 'Quantidade ou custo inválido';
    end if;
    purchase_total := purchase_total + item_quantity * item_cost;
  end loop;

  if payments is null or jsonb_typeof(payments) <> 'array'
     or jsonb_array_length(payments) = 0 then
    raise exception 'Informe ao menos uma forma de pagamento';
  end if;

  for payment in select * from jsonb_array_elements(payments) loop
    payment_method := trim(coalesce(payment ->> 'payment_method', ''));
    payment_amount := round((payment ->> 'amount')::numeric, 2);
    if payment_method = '' or payment_amount <= 0 then
      raise exception 'Forma ou valor de pagamento inválido';
    end if;
    payments_total := payments_total + payment_amount;
  end loop;

  if round(payments_total, 2) <> round(purchase_total, 2) then
    raise exception 'A soma dos pagamentos (%) deve ser igual ao total da compra (%)',
      payments_total, purchase_total;
  end if;

  select string_agg(distinct trim(value ->> 'payment_method'), ' + ')
  into payment_summary
  from jsonb_array_elements(payments);

  insert into public.product_purchases(
    supplier_id, numero_documento, data_compra, data_vencimento,
    forma_pagamento, total, observacao
  ) values (
    selected_supplier_id, nullif(trim(document_number), ''),
    coalesce(purchase_date, current_date),
    coalesce(due_date, purchase_date, current_date), payment_summary,
    purchase_total, nullif(trim(notes), '')
  ) returning id into new_purchase_id;

  for payment in select * from jsonb_array_elements(payments) loop
    payment_method := trim(payment ->> 'payment_method');
    payment_amount := round((payment ->> 'amount')::numeric, 2);

    insert into public.financial_entries(
      descricao, valor, tipo, forma_pagamento, status_pagamento,
      data_vencimento, origem, referencia_id
    ) values (
      format('Compra de produtos #%s - %s%s', new_purchase_id,
        selected_supplier.nome,
        case when nullif(trim(document_number), '') is null then ''
          else format(' - Documento %s', trim(document_number)) end),
      payment_amount, 'Despesa', payment_method, 'Pendente',
      coalesce(due_date, purchase_date, current_date), 'Compra PDV',
      new_purchase_id
    ) returning id into new_financial_entry_id;

    if first_financial_entry_id is null then
      first_financial_entry_id := new_financial_entry_id;
    end if;

    insert into public.product_purchase_payments(
      purchase_id, financial_entry_id, payment_method, amount, due_date
    ) values (
      new_purchase_id, new_financial_entry_id, payment_method, payment_amount,
      coalesce(due_date, purchase_date, current_date)
    );
  end loop;

  update public.product_purchases
  set financial_entry_id = first_financial_entry_id
  where id = new_purchase_id;

  for item in select * from jsonb_array_elements(items) loop
    select * into selected_product
    from public.products
    where id = (item ->> 'product_id')::bigint
    for update;

    item_quantity := (item ->> 'quantidade')::integer;
    item_cost := (item ->> 'custo_unitario')::numeric;
    stock_units := item_quantity * greatest(selected_product.units_per_purchase, 1);

    insert into public.product_purchase_items(
      purchase_id, product_id, quantidade, custo_unitario, subtotal
    ) values (
      new_purchase_id, selected_product.id, item_quantity, item_cost,
      item_quantity * item_cost
    );

    perform set_config('pet_maia.stock_kind', 'entrada', true);
    perform set_config('pet_maia.stock_reason',
      format('Compra #%s: %s %s = %s %s', new_purchase_id, item_quantity,
        selected_product.purchase_unit, stock_units, selected_product.sale_unit),
      true);
    update public.products
    set estoque = estoque + stock_units,
        stock_quantity = estoque + stock_units,
        preco_custo = item_cost / greatest(units_per_purchase, 1),
        updated_at = now()
    where id = selected_product.id;
  end loop;

  return new_purchase_id;
end;
$$;

revoke all on function public.create_product_purchase_split(
  bigint, text, date, date, jsonb, text, jsonb
) from public, anon, authenticated;
grant execute on function public.create_product_purchase_split(
  bigint, text, date, date, jsonb, text, jsonb
) to authenticated;
