create table public.pet_parasite_preventions (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  prevention_type text not null check (prevention_type in (
    'Vermífugo', 'Antipulgas', 'Carrapatos', 'Antipulgas e carrapatos', 'Outro'
  )),
  product_name text not null check (length(trim(product_name)) between 2 and 160),
  application_date date not null,
  next_application_date date,
  dose text,
  weight_kg numeric(8,3),
  batch_number text,
  professional_name text not null,
  notes text,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index pet_parasite_preventions_pet_date_idx
  on public.pet_parasite_preventions (pet_id, application_date desc);
create index pet_parasite_preventions_due_idx
  on public.pet_parasite_preventions (next_application_date)
  where next_application_date is not null;

alter table public.pet_parasite_preventions enable row level security;

create policy "Clinic users can manage parasite preventions"
on public.pet_parasite_preventions
for all
to authenticated
using (
  (select auth.uid()) is not null
  and (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  )
)
with check (
  (select auth.uid()) is not null
  and (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  )
);

revoke all on table public.pet_parasite_preventions from anon;
grant select, insert, update, delete on table public.pet_parasite_preventions to authenticated;
grant select, insert, update, delete on table public.pet_parasite_preventions to service_role;
grant usage, select on sequence public.pet_parasite_preventions_id_seq to authenticated;
grant usage, select on sequence public.pet_parasite_preventions_id_seq to service_role;
