create table if not exists public.clinical_patient_alerts (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  alert_type text not null check (alert_type in (
    'Alergia', 'Doença crônica', 'Medicação contínua', 'Cuidado especial', 'Outro'
  )),
  severity text not null default 'Atenção'
    check (severity in ('Informativo', 'Atenção', 'Crítico')),
  title text not null check (length(trim(title)) between 2 and 120),
  details text,
  active boolean not null default true,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists clinical_patient_alerts_pet_active_idx
  on public.clinical_patient_alerts (pet_id, active, severity);

alter table public.clinical_patient_alerts enable row level security;

drop policy if exists "Clinic users can manage patient alerts"
  on public.clinical_patient_alerts;
create policy "Clinic users can manage patient alerts"
on public.clinical_patient_alerts
for all
to authenticated
using (
  (select auth.uid()) is not null
  and (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  )
)
with check (
  (select auth.uid()) is not null
  and (
    public.current_user_can_access('clinica')
    or public.current_user_can_access('pets')
  )
);

revoke all on table public.clinical_patient_alerts from anon;
grant select, insert, update, delete on table public.clinical_patient_alerts
  to authenticated;
grant select, insert, update, delete on table public.clinical_patient_alerts
  to service_role;
grant usage, select on sequence public.clinical_patient_alerts_id_seq
  to authenticated;
grant usage, select on sequence public.clinical_patient_alerts_id_seq
  to service_role;

alter table public.clinical_records
  add column if not exists heart_rate integer
    check (heart_rate is null or heart_rate between 20 and 400),
  add column if not exists respiratory_rate integer
    check (respiratory_rate is null or respiratory_rate between 5 and 200),
  add column if not exists mucous_membranes text,
  add column if not exists hydration_status text,
  add column if not exists pain_score smallint
    check (pain_score is null or pain_score between 0 and 10);
