create table public.purchase_item_mappings (
  id bigint generated by default as identity primary key,
  destination_kind text not null check (destination_kind in ('pdv', 'grooming')),
  source_description text not null,
  normalized_description text not null,
  target_id bigint not null,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (destination_kind, normalized_description)
);

create index purchase_item_mappings_lookup_idx
  on public.purchase_item_mappings (destination_kind, normalized_description);

alter table public.purchase_item_mappings enable row level security;

create policy "Purchase users can manage item mappings"
on public.purchase_item_mappings
for all
to authenticated
using (
  (select auth.uid()) is not null
  and (
    public.current_user_can_access('pdv')
    or public.current_user_can_access('servicos')
  )
)
with check (
  (select auth.uid()) is not null
  and (
    public.current_user_can_access('pdv')
    or public.current_user_can_access('servicos')
  )
);

revoke all on table public.purchase_item_mappings from anon;
grant select, insert, update, delete on table public.purchase_item_mappings to authenticated;
grant select, insert, update, delete on table public.purchase_item_mappings to service_role;
grant usage, select on sequence public.purchase_item_mappings_id_seq to authenticated;
grant usage, select on sequence public.purchase_item_mappings_id_seq to service_role;
