insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'purchase-documents',
  'purchase-documents',
  false,
  15728640,
  array[
    'application/xml', 'text/xml', 'application/pdf', 'text/plain',
    'image/jpeg', 'image/png', 'image/webp'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table public.purchase_documents (
  id bigint generated by default as identity primary key,
  destination_kind text not null check (destination_kind in ('pdv', 'grooming')),
  linked_record_id bigint not null,
  document_number text,
  supplier_name text,
  original_name text not null,
  mime_type text not null,
  file_size bigint not null check (file_size > 0 and file_size <= 15728640),
  file_hash text not null check (file_hash ~ '^[a-f0-9]{64}$'),
  storage_path text not null unique,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  unique (file_hash)
);

create index purchase_documents_destination_idx
  on public.purchase_documents(destination_kind, linked_record_id);

alter table public.purchase_documents enable row level security;

create policy "Module users can read purchase documents"
  on public.purchase_documents for select to authenticated
  using (
    case destination_kind
      when 'pdv' then public.current_user_can_access('pdv')
      when 'grooming' then public.current_user_can_access('servicos')
      else false
    end
  );

create policy "Module users can insert purchase documents"
  on public.purchase_documents for insert to authenticated
  with check (
    created_by = (select auth.uid())
    and case destination_kind
      when 'pdv' then public.current_user_can_access('pdv')
      when 'grooming' then public.current_user_can_access('servicos')
      else false
    end
  );

create policy "Module users can upload purchase files"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'purchase-documents'
    and owner_id = (select auth.uid()::text)
    and case (storage.foldername(name))[1]
      when 'pdv' then public.current_user_can_access('pdv')
      when 'grooming' then public.current_user_can_access('servicos')
      else false
    end
  );

create policy "Module users can read purchase files"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'purchase-documents'
    and case (storage.foldername(name))[1]
      when 'pdv' then public.current_user_can_access('pdv')
      when 'grooming' then public.current_user_can_access('servicos')
      else false
    end
  );

create policy "Uploaders can delete unlinked purchase files"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'purchase-documents'
    and owner_id = (select auth.uid()::text)
  );

revoke all on public.purchase_documents from anon, authenticated;
grant select, insert on public.purchase_documents to authenticated;
grant usage, select on sequence public.purchase_documents_id_seq to authenticated;
