create table public.clinical_hospitalization_medications (
 id bigint generated by default as identity primary key,
 hospitalization_id bigint not null references public.clinical_hospitalizations(id) on delete cascade,
 medication text not null, dose text not null, route text not null, scheduled_at timestamptz not null,
 status text not null default 'Pendente' check (status in ('Pendente','Administrado')),
 administered_at timestamptz, administered_by text, notes text,
 created_at timestamptz not null default now(), created_by uuid default auth.uid() references auth.users(id) on delete set null
);
create index clinical_hosp_med_schedule_idx on public.clinical_hospitalization_medications(status,scheduled_at);
alter table public.clinical_hospitalization_medications enable row level security;
create policy "Clinic users can manage hospitalization medications" on public.clinical_hospitalization_medications for all to authenticated
using ((select auth.uid()) is not null and public.current_user_can_access('clinica'))
with check ((select auth.uid()) is not null and public.current_user_can_access('clinica'));
revoke all on public.clinical_hospitalization_medications from anon;
grant select,insert,update,delete on public.clinical_hospitalization_medications to authenticated,service_role;
grant usage,select on sequence public.clinical_hospitalization_medications_id_seq to authenticated,service_role;
